### PR TITLE
ecosystem: show product/services logos & flux ui screenshots

### PR DESCRIPTION
**Pull request by dholbach**
- show logos for all product/services providers who gave approval so far (D2iQ, Giant Swarm, Weaveworks)
- add Azure (thanks @pjbgf for getting confirmation)
- show screenshots of weave gitops

Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
Might need some additional styling: https://deploy-preview-1030--fluxcd.netlify.app/ecosystem/

**Comment by dholbach** [comment]
Weave GitOps Screenshots borrowed from https://fluxcd.io/blog/2022/04/march-update/#weave-gitops-core post.

**Comment by stefanprodan** [comment]
This looks good, can you please make the title of logos fit on a single line, if we rename the last 2 to "Gian Swarm" and "Weave GitOps" it should fit.

**Comment by dholbach** [comment]
cc @jonathan-innis

**Comment by dholbach** [comment]
I updated the gallery settings to be `thumbnailResizeOptions="600x600 q90 Lanczos"` - this looked better in my tests.

**Comment by dholbach** [comment]
cc @csand-msft

**Comment by csand-msft** [comment]
#sign-off

**Comment by csand-msft** [comment]
So, in the "Featured entries" table the header above the Azure icon should say "Azure".

In the "Complete list", the Product / Service should be "AKS + Azure Arc".

**Comment by dholbach** [comment]
Super. I think I got it this time - thanks for clarifying!

**Review by makkes — APPROVED** [review]
This looks much better than what we have now! Great job, @dholbach. 🥳 I'm fine with addressing the rest of my comments in a follow-up.

**Pull request merged**
