### PR TITLE
Add code snippet embed support

### PR DESCRIPTION
**Pull request by alisondy**
Adds the ability to read snippets from a file

Signed-off-by: Alison Dowdney <alison@alisondowdney.com>

### CODE REVIEW

**Review by dholbach — APPROVED** [review]
Nice work! Maybe propose it to docsy for inclusion as well?

**Comment by stefanprodan** [comment]
Does this work in tabs?

**Comment by alisondy** [comment]
shall investigate

**Comment by alisondy** [comment]
> Does this work in tabs?

see https://github.com/fluxcd/website/pull/401 for tabbed snippet and markdown support

**Pull request merged**
