### PR TITLE
Re-add docs

### PR DESCRIPTION
**Pull request by dholbach**
I'm mostly just throwing this up as a draft PR, so we all have a good idea of what we've already got through @hiddeco 's great work, what remains to be done.

A few things I can already see:
- we'll need to see where the docs will come from - will we use `hack/gen-content.sh`?
- not sure if we want the '0 minute read' for docs
- under `/docs` we might need to review how well the list of docs tiles will scale when we start adding more docs
- need to ensure "edit this page" works if we import docs from other repos

Apart from that great start already... :heart_eyes:

### CODE REVIEW

**Comment by dholbach** [comment]
cf https://deploy-preview-98--fluxcd.netlify.app/

**Comment by dholbach** [comment]
I added Flux v1 docs to try things out - looks like the links are broken.

**Comment by hiddeco** [comment]
> I added Flux v1 docs to try things out - looks like the links are broken.

I think the reason the links on the landing page are broken is because none of the pages have frontmatter, so they do not exist according to Hugo (and therefor no valid URL replacement is generated).

**Comment by dholbach** [comment]
```cli
❯ hugo server 
Start building sites … 
Built in 2 ms
Error: Error building site: process: readAndProcessContent: walk: Readdir: decorate: lstat /home/daniel/dev/fluxcd.io/content/en/docs/CONTRIBUTING.md: no such file or directory
```

Not quite sure why this happens. None of the command line options re: logging make any difference... :shrug:

**Comment by dholbach** [comment]
Builds work again: https://deploy-preview-98--fluxcd.netlify.app/docs/v2/ 

Lots of missing frontmatter, quite a bit of breakage - it will take a little while. 

What is the URL we'd like for v2 docs? fluxcd.io/docs/<..>?

@hiddeco @stefanprodan @scottrigby @mewzherder

**Comment by dholbach** [comment]
Following https://github.com/fluxcd/flux2/discussions/367/ now.

**Comment by dholbach** [comment]
- [ ] `!!!note`, etc will need to be replaced: cf https://deploy-preview-98--fluxcd.netlify.app/docs/get-started/

**Comment by hiddeco** [comment]
@dholbach they can be replaced with one of:

```
{{< note >}}This is a note.{{< /note >}}
{{< note title="Note" >}}This is a note with a title.{{< /note >}}
{{% note title="Note" %}}This is a note with a title and **Markdown**.{{% /note %}}
{{< note color="success" >}}This is a success note.{{< /note >}}
{{< note color="warning" >}}This is a warning.{{< /note >}}
{{< note color="warning" title="Warning" >}}This is a warning with a title.{{< /note >}}
```

**Comment by dholbach** [comment]
See a note in action: https://deploy-preview-98--fluxcd.netlify.app/docs/roadmap/

Progress bars are a bit less of a priority.

**Comment by dholbach** [comment]
```cli
content/en/docs on  readd-docs [$?] on ☁️ daniel@weave.works(europe-west1) 
❯ find . -iname '*.md'| grep -v "^.\/cmd" | wc -l
27
```

So apart from the auto-generated docs not too many files to fix.

**Comment by hiddeco** [comment]
> Progress bars are a bit less of a priority.

I think there was some chatter awhile ago that the percentage bar offered no real value, so we may just opt to remove them.

**Comment by dholbach** [comment]
All `!!!note` bits are replaced, in some cases I had to re-use backticks in the title. Let's fix this some time later.

**Comment by dholbach** [comment]
Things noted in various discussions:
- [ ] remove progressbars from roadmap doc
- [ ] figure out frontmatter for cmd doc (https://github.com/spf13/cobra/blob/master/doc/md_docs.md#customize-the-output)
- [ ] collapse docs menu by default (kind of like mkdocs-material on toolkit.fluxcd.io)
- [ ] smaller font, more info in viewport
- [ ] verify all docs are there and in a similar place as on toolkit.fluxcd.io

**Comment by dholbach** [comment]
Rebased on top of #104

**Comment by dholbach** [comment]
@scottrigby https://deploy-preview-98--fluxcd.netlify.app/docs/migration/timetable/ is a bit broken now. :man_shrugging:

**Comment by dholbach** [comment]
Superseded by #110 - moving tasks to https://github.com/orgs/fluxcd/projects/3

**Pull request closed without merging**
