### PR TITLE
Removed duplicate word

### PR DESCRIPTION
**Pull request by christiangonre**
Removed duplicate "the" word.

### CODE REVIEW

**Review by dholbach — APPROVED** [review]
Well spotted!

**Comment by dholbach** [comment]
git commit --amend --no-edit --signoff


git push --force-with-lease origin patch-2


 ^ Can you please run these commands?

**Comment by christiangonre** [comment]
Done!!
Thanks a lot for creating Flux, is awesome!

**Comment by dholbach** [comment]
Thanks for the kind words. Maybe you'd like to add your org to https://fluxcd.io/adopters?

**Pull request merged**
