### PR TITLE
Flux Graduation announcement

### PR DESCRIPTION
**Pull request by dholbach**
:warning: Only to be merged at around [9am Pacific Time](http://www.timebie.com/std/pst.php?q=9).

- The changes to the docs shall be reverted in about a week.
- The hero section can maybe be reset to what it was before in a month...?

### CODE REVIEW

**Comment by dholbach** [comment]
→ https://deploy-preview-1289--fluxcd.netlify.app/
→ https://deploy-preview-1289--fluxcd.netlify.app//docs (and subpages)
→ https://deploy-preview-1289--fluxcd.netlify.app/blog

**Comment by pjbgf** [comment]
On a larger monitor, the text in the announcement bar moves but is off centre:
image
As opposed to:
image

**Comment by dholbach** [comment]
Should be fixed now.

**Review by pjbgf — APPROVED** [review]
LGTM

It looks great, thank you @dholbach for working on this. :bow:

**Review by stefanprodan — APPROVED** [review]
🚀

**Pull request merged**
