### PR TITLE
Bring back Integrations page

### PR DESCRIPTION
**Pull request by dholbach**
Fixes: #302 

Sorry about the noise from #342 and its rollback. We are now going with a simple table and will extend and beautify it over the next iterations.

### CODE REVIEW

**Comment by paulcarlton-ww** [comment]
I am not the owner of Kraan, it is a Fidelity project, I'm no longer a maintainer, they removed me from the org when I my Fidelity engagement finished. I did mail @rajarajanpsj who is the engineering director about inclusion on the adopter page.

**Comment by dholbach** [comment]
> I am not the owner of Kraan, it is a Fidelity project, I'm no longer a maintainer, they removed me from the org when I my Fidelity engagement finished. I did mail @rajarajanpsj who is the engineering director about inclusion on the adopter page.

It's the integrations page, but thanks a lot for passing this on @paulcarlton-ww . In my opinion, as all of these integrations are public on GitHub, I assume that this is less of an issue.

Being on the `/adopters` page is a different issue.

**Comment by paulcarlton-ww** [comment]
> > I am not the owner of Kraan, it is a Fidelity project, I'm no longer a maintainer, they removed me from the org when I my Fidelity engagement finished. I did mail @rajarajanpsj who is the engineering director about inclusion on the adopter page.
> 
> It's the integrations page, but thanks a lot for passing this on @paulcarlton-ww . In my opinion, as all of these integrations are public on GitHub, I assume that this is less of an issue.
> 
> Being on the `/adopters` page is a different issue.

@dholbach I'd still get permission from Fidelity before using their logo,

**Review by pzfreo — COMMENTED** [review]
The Weave GitOps entry looks good to me

**Review by hiddeco — APPROVED** [review]
Thank you @dholbach 🥮

**Pull request merged**
