### PR TITLE
Move docs from f/flux2 to fluxcd.io, move to docsy theme as well

### PR DESCRIPTION
**Pull request by dholbach**

### CODE REVIEW

**Comment by dholbach** [comment]
- [ ] replace slant thing with gradient
- [ ] grey should be less depressing
- [ ] youtube preview on mobile
- [ ] hover link colour
- [ ] top navbar loses links when going into mobile phone view

**Comment by dholbach** [comment]
@juozasg This change seems to help with keeping the search bar in a mobile world

```diff
diff --git layouts/partials/navbar.html layouts/partials/navbar.html
index 43d24c4..55fe8d9 100644
--- layouts/partials/navbar.html
+++ layouts/partials/navbar.html
@@ -44,5 +44,5 @@
                        {{ end }}
                </ul>
        </div>
-       <div class="navbar-nav d-none d-lg-block">{{ partial "search-input.html" . }}</div>
+       <div class="navbar-nav d-lg-block">{{ partial "search-input.html" . }}</div>
 </nav>
```

The **Project** menu disappears depending on the screen width though.

**Comment by dholbach** [comment]
I wonder if we need to look at https://getbootstrap.com/docs/4.6/components/navbar/#responsive-behaviors for this?

**Comment by dholbach** [comment]
I've played around with bootstrap navbar bits and got this far:

```diff
diff --git layouts/partials/navbar.html layouts/partials/navbar.html
index 43d24c4..8dfbc1e 100644
--- layouts/partials/navbar.html
+++ layouts/partials/navbar.html
@@ -1,13 +1,17 @@
 {{ $cover := .HasShortcode "blocks/cover" }}
-<nav class="js-navbar-scroll navbar navbar-expand navbar-dark {{ if $cover}} td-navbar-cover {{ end }}flex-column flex-md-row td-navbar">
-        <a class="navbar-brand" href="{{ .Site.Home.RelPermalink }}">
+<nav class="js-navbar-scroll navbar navbar-expand-md navbar-dark {{ if $cover}} td-navbar-cover {{ end }}flex-column flex-md-row td-navbar">
+    <a class="navbar-brand" href="{{ .Site.Home.RelPermalink }}">
                <span class="navbar-logo">{{ if .Site.Params.ui.navbar_logo }}{{ with resources.Get "icons/logo.svg" }}{{ ( . | minify).Content | safeHTML }}{{ end }}{{ end }}</span><span>{{ .Site.Title }}</span>
        </a>
+       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
+               <span class="navbar-toggler-icon"></span>
+       </button>
+       <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="td-navbar-nav-scroll ml-md-auto" id="main_navbar">
                <ul class="navbar-nav mt-2 mt-lg-0">
                        {{ $p := . }}
                        {{ range .Site.Menus.main }}
-                       <li class="nav-item mr-4 mb-2 mb-lg-0">
+                       <li class="nav-item">
                                {{ $active := or ($p.IsMenuCurrent "main" .) ($p.HasMenuCurrent "main" .) }}
                                {{ with .Page }}
                                {{ $active = or $active ( $.IsDescendant .)  }}
@@ -27,7 +31,7 @@
             </div>
           </li>
                          {{ else }}
-        <li class="nav-item mr-4 mb-2 mb-lg-0">
+        <li class="nav-item">
           <a class="nav-link{{if $active }} active{{end}}" href="{{ with .Page }}{{ .RelPermalink }}{{ else }}{{ .URL | relLangURL }}{{ end }}" {{ if ne $url.Host $baseurl.Host }}target="_blank" {{ end }}><span{{if $active }} class="active"{{end}}>{{ .Name }}</span></a>
         </li>
                          {{ end }}
@@ -44,5 +48,6 @@
                        {{ end }}
                </ul>
        </div>
-       <div class="navbar-nav d-none d-lg-block">{{ partial "search-input.html" . }}</div>
+       <div class="navbar-nav d-lg-block">{{ partial "search-input.html" . }}</div>
+</div>
 </nav>
```

Screenshot from 2021-04-20 11-05-02
Screenshot from 2021-04-20 11-05-24

Is this a direction we'd like to go? If yes, as you can see it's not working perfectly yet ... help? (I don't really know what I'm doing...)

**Comment by bia** [comment]
@dholbach could this hamburger menu behave like [squarespace](https://www.squarespace.com/templates/bailard-demo)?

chrome-capture

**Comment by dholbach** [comment]
@bia This looks very nice - I'm just not sure how easy or hard it is to implement it. Docsy uses Bootstrap...? :man_shrugging: 

For now I'd be happy with anything which works and doesn't leave users wondering where the links are. :grimacing: 

I'd like to able for us to review this PR this week (and I'll need to feed in docs changes and other bits too still).

**Comment by dholbach** [comment]
Regarding the gap between gradient and "GitOps at your fingertips" - this seems to help:

```diff
diff --git layouts/shortcodes/blocks/hero.html layouts/shortcodes/blocks/hero.html
index 87d3dc5..fe14913 100644
--- layouts/shortcodes/blocks/hero.html
+++ layouts/shortcodes/blocks/hero.html
@@ -26,7 +26,7 @@
   }
 </style>
 {{ end }}
-<section id="{{ $blockID }}" class="row td-hero-block td-overlay -bg-{{ $col_id }} ">
+<section id="{{ $blockID }}" class="row td-hero-block -bg-{{ $col_id }} ">
   <div class="container td-overlay__inner" style="padding: 20px;">
       <div class="row">
         <div class="col-md">
```

**Comment by dholbach** [comment]
> Regarding the gap between gradient and "GitOps at your fingertips" - this seems to help:
> 
> [..]

This was a premature - unfortunately it doesn't work.

**Comment by dholbach** [comment]
@alisondy @bia @hiddeco @scottrigby Would anyone be up for picking colours :art: 
- to replace the currently grey bits in the resources section: https://deploy-preview-130--fluxcd.netlify.app/
- which works for links that are being hovered over
- which work better in alerts like at the top of https://deploy-preview-130--fluxcd.netlify.app/docs/migration/flux-v1-migration/ - maybe use boxes instead?

**Comment by alisondy** [comment]
re colors:

Grey as #2f2f2f
GitOps toolkit box, Other Flux Projects , same as top, fingertips #3d6ddd
Flagger box, as green on flagger site #3eaf7c
Community use Grey #2f2f2f

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @dholbach for all the work on this 🤗 

I propose we merge as it is and iterate on it afterwords. The website main page looks really good now.

**Comment by dholbach** [comment]
A couple of comments before we merge this:

- Thanks @alisondy for your help on moving us to `google/docsy` and many other improvements
- Thanks @hiddeco for advice and help along the way
- Thanks @juozasg for being the css :firefighter: when we needed one
- Thanks @kingdonb and @stefanprodan for reviews, tips
- Thanks entire team for advice, reviews, help and support

- Docs are up to https://github.com/fluxcd/flux2/commit/15ebfd7eb6d83f575048ffebf1dcf68d53d50233 and we'll keep on maintaining docs in both places for a little while.
- I'll file issues for the outstanding bits
- I will also inform the entire Flux dev team about this change and what to bear in mind when writing docs

**Comment by dholbach** [comment]
Oh and one more thing: sorry for the big mess the commit history is - we worked across 3 forks and multiple branches. With my limited `git` skills, I manage to squash >150 to `48` today where logical grouping was easy to do, but that's as good as it gets if nobody else want to reengineer the commit history.

**Pull request merged**
