### PR TITLE
simplify hugo setup

### PR DESCRIPTION
**Pull request by dholbach**
- Use same pip call everywhere
-  Stop pulling in `hugo-extended` through `npm` - we don't use it.
	We already explain to install the extended version of hugo. `npm i` will install the hugo node module, but it doesn't
	install the binary in the PATH. For Netlify and the docker image we install hugo through other means.

	Overall this is a little improvement on #434, but likely not the best outcome yet.

### CODE REVIEW

**Comment by dholbach** [comment]
After this is applied, we are down to these definitions of hugo versions:

```cli
❯ git grep "0\.88\.1"
Dockerfile:FROM fluxcd/website:hugo-0.88.1-extended
Makefile:HUGO_VERSION               ?= 0.88.1
netlify.toml:  HUGO_VERSION = "0.88.1"

website on  one-less-hugo-mention via  v14.17.6 via 🐍 v3.8.10 
❯ 
```

**Comment by dholbach** [comment]
@kingdonb tested this and is happy to approve.

@stefanprodan Do you think you could merge and then run

```cli
rm -rf hugo/   # (to remove any stale artifacts from the previous image build)
make docker-push
```
to update the `fluxcd/website` images?

**Comment by kingdonb** [comment]
I don't think it gets much better than this 👍 

I did:
```
rm -rf hugo/
make hugo
make docker-build-hugo
make docker-build-support
make docker-preview
```

and I am seeing the preview just fine on http://localhost:1313 👍 LGTM

@stefanprodan if you can update the image after this is done, then the docker-preview instructions should work again for anyone and match the latest version,

Once this merges to the main branch, if you check it out first, then this should be all you need to run, assuming you are also already logged in with credentials that can push to the `fluxcd/website` repo:

```
## Note: you may or may not have stale `hugo/` directory lying around already
rm -rf hugo/       # (to remove any stale artifacts from the previous image build)
make docker-push
```

This will build two images, and push both images. Here is the push target, for reference, so we can see when it has been updated:

https://hub.docker.com/r/fluxcd/website/tags?page=1&ordering=last_updated

People who run `make docker-preview` or `okteto up` will depend on this image, `fluxcd/website:hugo-support`

It is not versioned, and this is on purpose. It could probably be simplified somewhat. The build step takes quite a bit of time, and is still a manual step, but I think we don't update the base of the website that often, so hopefully that is OK. 👍

**Comment by dholbach** [comment]
> I don't think it gets much better than this +1

@kingdonb How do you feel about something like this?

```diff
diff --git a/Makefile b/Makefile
index 3b4b11e..01c5590 100644
--- a/Makefile
+++ b/Makefile
@@ -14,7 +14,7 @@ FONT_AWESOME_SEMVER_FOLDER := Font-Awesome-$(FONT_AWESOME_SEMVER)
 FONT_AWESOME_TARGET        := themes/$(DOCSY_COMMIT_FOLDER)/assets/vendor/$(FONT_AWESOME_SEMVER_FOLDER)
 
 DEV_IMAGE_REGISTRY_NAME    ?= fluxcd
-HUGO_VERSION               ?= 0.88.1
+HUGO_VERSION               ?= $(shell grep HUGO_VERSION netlify.toml | cut -d'"' -f2)
 HUGO_IMAGE_BASE_NAME       := website:hugo-$(HUGO_VERSION)-extended
 SUPPORT_IMAGE_BASE_NAME    := website:hugo-support
 HUGO_IMAGE_NAME            ?= $(DEV_IMAGE_REGISTRY_NAME)/$(HUGO_IMAGE_BASE_NAME)
```

**Comment by kingdonb** [comment]
Yes, that change LGTM, unfortunately I'm fairly certain we can't perform the same or similar trick in the Dockerfile.

**Comment by alisondy** [comment]
LGTM

**Review by alisondy — APPROVED** [review]

**Pull request merged**
