### PR TITLE
Add Volvo Cars to adopters

### PR DESCRIPTION
**Pull request by brovoca**
Signed-off-by: Emil Dabrowski <emil.dabrowski@volvocars.com>

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
Thank you @brovoca 🏅 

PS. I love my Volvo car 😄

**Comment by brovoca** [comment]
@stefanprodan We're really happy to hear! :D We very much enjoy working with FluxCD and really appreciate the help you guys are giving in the Slack channel!

**Comment by mewzherder** [comment]
@brovoca Thanks so much!! ❤️  Any chance our community managers can chat with you or your team to hear how you're using flux and get your feedback? Please lmk and thanks again for taking the time to add yourself!! 🧸

**Comment by brovoca** [comment]
@mewzherder Sure, I think that could be something we could arrange! 😇

**Comment by mewzherder** [comment]
@brovoca awesome! ❤️  I guess I'll email you? Look for subject line "chat about Flux" I guess :D Thanks!!!

**Pull request merged**
