### PR TITLE
Add William & Mary to adopters

### PR DESCRIPTION
**Pull request by pcfens**

### CODE REVIEW

**Comment by kingdonb** [comment]
Looks good to me @pcfens – thanks for submitting this!

Can you have a look at the deploy preview and let me know if you satisfied with the look of the logo before I merge this?

https://deploy-preview-697--fluxcd.netlify.app/

👍

**Review by kingdonb — APPROVED** [review]
👍

**Comment by pcfens** [comment]
Thanks for pointing that out. After a few tries (and too many official logo variations). This one seems to work the best.

**Comment by kingdonb** [comment]
SVG! Nice, I think that does look better.

**Pull request merged**
