### PR TITLE
Use Algolia search

### PR DESCRIPTION
**Pull request by dholbach**
Fixes: #196

### CODE REVIEW

**Comment by dholbach** [comment]
Not sure if we can test this before it's moved to `fluxcd.io`.

I followed all the steps listed in https://www.docsy.dev/docs/adding-content/navigation/#configure-algolia-docsearch - the css/js is loaded fine, but maybe it's because the config just lists fluxcd? https://github.com/algolia/docsearch-configs/blob/master/configs/fluxcd.json

Shall we merge it and roll back if it doesn't work?

**Comment by dholbach** [comment]
The Algolia search is working now - MUCH better! <3

**Comment by scottrigby** [comment]
Just a note to override the partial and file upstream issue. Tired kubecon convo in slack 😅

**Review by scottrigby — APPROVED** [review]
Looks good! only thing is, could we adjust docssearch-configs to traverse the top level above docs too, so that it picks up blogs, adopters, etc?

https://github.com/algolia/docsearch-configs/blob/5b9967e3d0124868fcd315ecb4b532c0b36d787d/configs/fluxcd.json#L4

Could be a follow up, that's my only other question so approving too 💯

**Comment by dholbach** [comment]
> Looks good! only thing is, could we adjust docssearch-configs to traverse the top level above docs too, so that it picks up blogs, adopters, etc?
> 
> https://github.com/algolia/docsearch-configs/blob/5b9967e3d0124868fcd315ecb4b532c0b36d787d/configs/fluxcd.json#L4
> 
> Could be a follow up, that's my only other question so approving too 100

I sent a mail to Algolia to ask.

**Pull request merged**
