### PR TITLE
Make Flux UIs more obvious and show images in more than one place

### PR DESCRIPTION
**Pull request by dholbach**
This a bit of a hack, and I would appreciate some help styling this more nicely.

Unfortunately can [the gallery theme we use](https://github.com/mfg92/hugo-shortcode-gallery) only show images which are in a page bundle, so a situation like this (or similar):

```
directory/
    index.md
    img1.png
    img2.png
```

Doing this across various places would need us

1. duplicate images and 
2. potentially having to update across many places as well

I created a re-usable partial with Bootstrap's [Card Group](https://getbootstrap.com/docs/4.6/components/card/#card-groups), [Modal](https://getbootstrap.com/docs/4.6/components/modal/) and [Carousel](https://getbootstrap.com/docs/4.6/components/carousel/). Unfortunately I couldn't use Carousel controls or indicators as the modal already uses the "data-target" argument.

Help or feedback is welcome!

Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
Image galleries are now shown not only at https://deploy-preview-1359--fluxcd.netlify.app/ecosystem/ as before, but also at

- https://deploy-preview-1359--fluxcd.netlify.app/flux
- https://deploy-preview-1359--fluxcd.netlify.app/faq

Happy to make them a bit smaller or alter in any way you see would like to.

**Comment by dholbach** [comment]
cc @Callisto13

**Comment by dholbach** [comment]
https://fluxcd.io/ecosystem/#flux-uis--guis is the section we had before, using the gallery theme we have been using up until now, as a comparison.

**Review by Arhell — COMMENTED** [review]
lgtm

**Comment by stefanprodan** [comment]
@dholbach please use only two pics for VS code and switch the order, wego first. For wego please use these two pics:
- https://github.com/stefanprodan/gitops-linkerd/blob/main/docs/screens/wego-apps.png
- https://github.com/stefanprodan/gitops-linkerd/blob/main/docs/screens/wego-deps.png

**Comment by dholbach** [comment]
Thanks for the feedback, will do later.

**Comment by makkes** [comment]
The Weave GitOps screenshots are completely unreadable on my machine. We need to make new ones. I can try to find some time for that later this week.

**Comment by stefanprodan** [comment]
> The Weave GitOps screenshots are completely unreadable on my machine.

Which ones? Mine look ok, check out my repo readme

**Comment by dholbach** [comment]
:heavy_check_mark:

**Review by stefanprodan — APPROVED** [review]

**Comment by dholbach** [comment]
Thanks @stefanprodan for the help!

**Comment by makkes** [comment]
@stefanprodan @dholbach

**Comment by dholbach** [comment]
Try the screenshots in https://github.com/fluxcd/website/pull/1359#issuecomment-1403468718

They are not on https://fluxcd.io/ecosystem - are they good for you?

**Comment by makkes** [comment]
> Try the screenshots in [#1359 (comment)](https://github.com/fluxcd/website/pull/1359#issuecomment-1403468718)
> 
> They are now on https://fluxcd.io/ecosystem - are they good for you?

They look pretty much the same from a readability perspective. 🤔 Is it just my browser showing them so tiny?

**Pull request merged**
