### PR TITLE
Update HelmRelease creation example

### PR DESCRIPTION
**Pull request by hiddeco**
...and update the example output to match what's generated with the command.

### CODE REVIEW

**Comment by stefanprodan** [comment]
traefik is a bad example to give as it requires a LoadBalancer and lots of resources, making this tutorial fail on anyones laptop.

**Comment by hiddeco** [comment]
Forgot I had created this PR, what other chart would be a better example?

**Comment by hiddeco** [comment]
I suspect @scottrigby used the example that is typically used with Helm, but I may be wrong.

**Comment by stefanprodan** [comment]
@hiddeco I would use something that's validated by e2e tests, e.g. https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/infrastructure/nginx/release.yaml

**Comment by dholbach** [comment]
#414 fixes this similarly...?

**Comment by scottrigby** [comment]
Also changing the example chart may be better as a follow-up to this PR, which just updates the example to match CLI output?

**Comment by dholbach** [comment]
Looks like #414 addresses some additional things: https://github.com/fluxcd/website/pull/414#issuecomment-888348279

**Comment by scottrigby** [comment]
> Looks like #414 addresses some additional things: #414 (comment)

@dholbach I commented in that other PR: https://github.com/fluxcd/website/pull/414#issuecomment-890078841 Tl;dr, I believe this one is the correct CLI output fix/update.


> @hiddeco I would use something that's validated by e2e tests, e.g. https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/infrastructure/nginx/release.yaml

@stefanprodan I created a new issue for this that explains the benefits you noted, as well as my comment about which version of ingress-nginx chart we should use if we do: https://github.com/fluxcd/website/issues/436

**Review by scottrigby — APPROVED** [review]

**Pull request merged**
