### PR TITLE
add missing hostname parameter

### PR DESCRIPTION
**Pull request by Robbilie**

### CODE REVIEW

**Comment by stefanprodan** [comment]
@Robbilie please signoff your commit, instructions here https://github.com/fluxcd/website/pull/875/checks?check_run_id=5886374993

**Comment by Robbilie** [comment]
well after some fighting against my global git config, there we go, rebased and signed off :)
out of curiosity, whats the reasoning for including this?

**Review by stefanprodan — APPROVED** [review]
LGTM 

Thanks @Robbilie

**Comment by stefanprodan** [comment]
@Robbilie Flux is a CNCF project, all Linux Foundation projects required some form of DCO. You can read more about what it means here: https://fluxcd.io/docs/contributing/flux/#certificate-of-origin

**Comment by Robbilie** [comment]
Thanks for the link @stefanprodan :)

**Pull request merged**
