### PR TITLE
Import fluxcd/flagger docs

### PR DESCRIPTION
**Pull request by dholbach**
Currently up at rev [95381e1892a43a167b0894f583894da2a7067123](https://github.com/fluxcd/flagger/commit/95381e1892a43a167b0894f583894da2a7067123)

- Add nav entries (frontmatter)
- Import diagrams and screens - use local images (not hotlink GitHub)
- Import redirects too
- Local links everywhere
- Conditionalise logo and docs link in navbar
- Move Flagger project to top of projects section on landing page

Fixes: #894

Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
TODO

- [ ] add separate Flagger search
- [ ] double-check we caught everything
- [ ] Later: replace flagger.app with redirects (we'll have both sites available for some time)

**Comment by dholbach** [comment]
→ https://deploy-preview-903--fluxcd.netlify.app/flagger/

**Comment by stefanprodan** [comment]
We need to replace `Introduction` with `Flagger`
Screenshot 2022-04-29 at 13 38 57

**Comment by dholbach** [comment]
TODO

- [ ] add separate Flagger search
- [ ] decide on where else to place Flagger in nav
- ~~add Flagger main page, use 'intro' for docs content, adjust links~~
- [x] on /flagger show flagger logo in top nav (top left) (need help)
- [ ] double-check we caught everything
- [ ] Redesign fluxcd.io/flagger page - integrate bits from https://flagger.app/ (I'll need help with this - probably later?)
- [ ] Later: replace flagger.app with redirects (we'll have both sites available for some time)

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @dholbach 🥇 

PS. Let's create an issue for the Flagger home page and roadmap.

**Pull request merged**
