### PR TITLE
Generate /resources page from YAML

### PR DESCRIPTION
**Pull request by dholbach**
Addresses big part of: #1205

Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
The diff in generated markdown is neglectible, typos, date inconsistencies, order: https://gist.github.com/dholbach/818d4f4a2381e7641b11183286de0197

**Review by stefanprodan — APPROVED** [review]
LGTM

Great improvement @dholbach 🏅

**Comment by dholbach** [comment]
In a next step, we can move the resources section on https://fluxcd.io to be auto-generated as well, e.g. "last 6 entries which have `featured: true`".

**Comment by dholbach** [comment]
→ https://deploy-preview-1207--fluxcd.netlify.app/resources/

**Pull request merged**
