### PR TITLE
landing page: remove terminal for now

### PR DESCRIPTION
**Pull request by dholbach**
Remove terminal for now.

Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
→ https://deploy-preview-1362--fluxcd.netlify.app/

**Comment by stefanprodan** [comment]
We need to update the terminal as it shows Flux bootstrap from one or two years ago, things have changed a lot I think.

**Comment by dholbach** [comment]
@hiddeco Do you think you can help with this? I'm not sure how this was done or set up...

**Comment by stefanprodan** [comment]
I also see a major improvement on iOS with the current home page, the slowness seems to be due to the terminal rendering.

**Comment by dholbach** [comment]
If we feel we are good to go without the terminal, there's quite a lot of code we can remove from `f/website`.

**Comment by hiddeco** [comment]
As I do not have time at present to re-do the whole recording, in combination with Stefan's comments about mobile problems etc. I am fine with removing it for now.

**Review by kingdonb — APPROVED** [review]
👍

**Pull request merged**
