### PR TITLE
Update namespace of kubectl command

### PR DESCRIPTION
**Pull request by gangstead**
The port-forward needs to use the namespace `monitoring` since that's the [namespace created by the kube-prometheus-stack kustomization](https://github.com/fluxcd/flux2/blob/main/manifests/monitoring/kube-prometheus-stack/namespace.yaml#L4)

### CODE REVIEW

**Comment by dholbach** [comment]
Thanks for the PR @gangstead - can you please run these commands?

```cli
git rebase HEAD~2 --signoff
git push --force-with-lease origin patch-1
```

**Comment by dholbach** [comment]
@SomtochiAma Does the PR look good to you?

**Comment by gangstead** [comment]
signed off and pushed

**Review by stefanprodan — APPROVED** [review]
LGTM 

Thanks @gangstead

**Pull request merged**
