### PR TITLE
Adding Capacitor to the Ecosystem page

### PR DESCRIPTION
**Pull request by laszlocph**

### CODE REVIEW

**Comment by stefanprodan** [comment]
Please move it first in the table and in the screen section as we use alphabetical ordering.

**Comment by stefanprodan** [comment]
@laszlocph you can see the preview here https://deploy-preview-1819--fluxcd.netlify.app/ecosystem/

The screens are not good, it loads VS code

**Comment by laszlocph** [comment]
Now it's ready. (I pushed a few debug commits as the carousel was a bit wonky)

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @laszlocph 🥇

**Pull request merged**
