### PR TITLE
feat: add DoneOps to adopters page

### PR DESCRIPTION
**Pull request by jmymy**

### CODE REVIEW

**Comment by dholbach** [comment]
Working on https://6398a6856cecae5d65863485--fluxcd.netlify.app/adopters/, so merging now! Thanks.

**Review by dholbach — APPROVED** [review]

**Review by scottrigby — APPROVED** [review]
lgtm!

**Comment by dholbach** [comment]
The build passes in Netlify now, but it doesn't seem to report this back to GitHub, or something. :man_shrugging:

**Comment by jmymy** [comment]
hrrmmm the logo isn't updated on the support page. are netlify builds just really behind?

**Pull request merged**
