### PR TITLE
Resource page update to include external articles/blogs

### PR DESCRIPTION
**Pull request by kingdonb**
Rebased from:

* #1693 

To address the Flux request for CNCF tech docs team, in https://github.com/cncf/techdocs/issues/192

Thank you @thisisobate!

### CODE REVIEW

**Comment by kingdonb** [comment]
@thisisobate Can you explain some of the javascript code changes? I see that you mentioned them in your todo list but I'm not understanding what the search code changes are for. There doesn't seem to be any search on the resources page.

**Comment by thisisobate** [comment]
So here's a brief summary of how I implemented the filter:

So the filter functions as a search under the hood. The idea is that once a user selects the items to filter, it will now query the index to see if there's a match. If true, it returns the matched record and then renders it on the DOM.

While thinking about this problem, I considered alot of things like internalization and advanced search capabilities. I then decided to use the [Lunrjs](https://lunrjs.com/) search package to power the resource filter.

@kingdonb

**Comment by kingdonb** [comment]
Thanks! I think this looks good, but I can't merge it myself. As soon as someone else is able to review it, I think it's LGTM

**Comment by kingdonb** [comment]
I would like to rebase and merge this soon. If any objections, please speak up. Targeting merge later on today.

We can use it to promote the Botkube and Flux integration post that @mashby2022 is planning, but I see no issues with merging this as-is (I will rebase it first, preserving the commit authorship as much as possible.)

Thanks again @thisisobate ! And thanks to the CNCF team at large

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @thisisobate and @kingdonb 🏅

**Comment by thisisobate** [comment]
Hi @kingdonb @stefanprodan 
For some reason, the website is yet to show the latest update. 
Please take a look.
Thanks!

**Comment by kingdonb** [comment]
We looked into it, there is a backport label that needs to be applied, I haven't been merging a lot of PRs to the website since GA so I did not know about it...

You can see the result of the merge on:

https://main.docs.fluxcd.io/

I'll figure out the backporting labels today so that it makes it to FluxCD.io proper - this is a user error problem and it's my problem 😅

**Comment by thisisobate** [comment]
Oh...thought as much 😅
Thanks for the clarification

**Comment by kingdonb** [comment]
That worked, it's deployed live and you can see it now:

https://fluxcd.io/resources/

🚀 🎉

**Pull request merged**
