### PR TITLE
Add Gimlet to Ecosystem products

### PR DESCRIPTION
**Pull request by makkes**

### CODE REVIEW

**Comment by laszlocph** [comment]
:rocket:

**Comment by dholbach** [comment]
Thanks for your PR, @laszlocph 

Can you please sign your commit?

- In your local branch, run: `git rebase HEAD~1 --signoff`
- Force push your changes to overwrite the branch: `git push --force-with-lease origin add-gimlet`

**Comment by makkes** [comment]
> Thanks for your PR, @laszlocph
> 
> Can you please sign your commit?
> 
>     * In your local branch, run: `git rebase HEAD~1 --signoff`
> 
>     * Force push your changes to overwrite the branch: `git push --force-with-lease origin add-gimlet`

Sorry, that's on me actually. Pushed signed-off commit now.

**Review by dholbach — APPROVED** [review]
Thanks everyone!

**Pull request merged**
