### PR TITLE
docs: show best-practice OSS we integrate with

### PR DESCRIPTION
**Pull request by dholbach**
Fixes: #898

Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
After some feedback, 1) move to `/docs` page and 2) turn the logos into links to relevant docs.

Obviously we want to add more logos to this - as Stefan said, we could link to all the other OSS pieces Flagger integrates with (and we have docs for) - any hints or pointers are welcome!

**Comment by dholbach** [comment]
→ https://deploy-preview-1079--fluxcd.netlify.app/docs/

**Comment by stefanprodan** [comment]
I think we need to use logos of same size, @dholbach please use something like https://www.iloveimg.com/ to also shrink their sizes. Also let's add another one, Linkerd to have 8 logos.

**Comment by dholbach** [comment]
Almost all the logos are SVG - I could imagine that it's CSS trick to get them all to equal size. And sure, happy to add Linkerd.

**Comment by stefanprodan** [comment]
Ok then please find a SVG for SOPS too.

**Comment by dholbach** [comment]
How do you like it now?

**Comment by stefanprodan** [comment]
Looks good now! thanks

**Comment by dholbach** [comment]
Replaces: #1054

**Review by pjbgf — APPROVED** [review]
LGTM

thanks @dholbach :bow:

**Pull request merged**
