### PR TITLE
Remove duplicate AWS EKS Anywhere and Weave GitOps entries

### PR DESCRIPTION
**Pull request by dholbach**
- AWS EKS Anywhere was already listed under Product/Services
- Weave GitOps was already listed under UIs

Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
I was considering moving `weaveworks/vscode-gitops-tools` under UIs as well ... WDYT?

**Review by stefanprodan — APPROVED** [review]

**Comment by dholbach** [comment]
@kingdonb what do you think about moving the Vs code entry?

**Comment by kingdonb** [comment]
@dholbach Yes I agree, "Extensions" is technically correct but in a slightly upside-down sense, because this is not a Flux extension it's a VSCode extension for Flux.

If we had a new section or page for Flux UIs then the VS Code Extension should go there. 👍

**Comment by dholbach** [comment]
We do... https://fluxcd.io/ecosystem/#flux-uis :-)

**Comment by kingdonb** [comment]
Got it! I'll send a PR

**Comment by dholbach** [comment]
I can do it do - no problemo.

**Comment by kingdonb** [comment]
Here it is: https://github.com/fluxcd/website/pull/1064

**Pull request merged**
