### PR TITLE
Update to latest docsy

### PR DESCRIPTION
**Pull request by dholbach**
Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
Since there were some upstream white-space changes, here is our current diff over Docsy partials: https://gist.github.com/dholbach/8bef68721db91a4ea874a6975d27902d

Maybe we should do a review of it some time to make sure it doesn't get too big and unmaintainable.

**Comment by dholbach** [comment]
→ https://deploy-preview-1134--fluxcd.netlify.app/
→ https://deploy-preview-1134--fluxcd.netlify.app/blog/
→ https://deploy-preview-1134--fluxcd.netlify.app/flagger/
→ https://deploy-preview-1134--fluxcd.netlify.app/flux/

All tested with mobile mode as well.

**Review by Arhell — APPROVED** [review]
I looked at the pages, both PC and mobile are in order.
Thanks!

**Comment by dholbach** [comment]
I just went over all our overridden partials to document when and how we changed them. See the gist above for the current diff over upstream. If we could minimise any of this, that would be great. :-D

**Review by scottrigby — APPROVED** [review]
lgtm 👍 also nice addition of comments @dholbach 🙌 
just to be clear, this updates to most recent version of docsy, and adds comments to help for future. Pages all look great

**Pull request merged**
