### PR TITLE
Move happn to Flux2 adopters

### PR DESCRIPTION
**Pull request by Frizlab**

### CODE REVIEW

**Review by dholbach — CHANGES_REQUESTED** [review]
Can you please run the following commands?

```cli
git commit --amend --no-edit --signoff
git push --force-with-lease origin add_happn
```

We require DCO.

**Comment by dholbach** [comment]
And thanks a lot for being part of the community @Frizlab!

**Comment by Frizlab** [comment]
Signed off with my work email! 😉

**Comment by dholbach** [comment]
Hey, so for some reason the DCO check still goes off: https://github.com/fluxcd/website/pull/292/checks?check_run_id=2675232724 - it seems to be specific about which email it would like to see. Maybe it's a `config.user` kind of git setting? :man_shrugging:

**Comment by Frizlab** [comment]
Apparently the sign-off email and committer email must be equal for whatever reasons 🤷‍♂️
Pushed again; should be good!

**Review by dholbach — APPROVED** [review]

**Comment by dholbach** [comment]
Third time lucky.

**Pull request merged**
