### PR TITLE
Adding GitOpsDays Sessions

### PR DESCRIPTION
**Pull request by vanessaabankwah**
GitOps in Microsoft Azure with Flux by Chris Sanders & Jonathan Innis

Signed-off-by: Vanessa Abankwah  <96237690+VanessaWeaveworksK8S@users.noreply.github.com>

### CODE REVIEW

**Review by staceypotter — CHANGES_REQUESTED** [review]
Thanks for adding this to the videos resources. But, I think it should be the first video listed according to the date. (Not that you could tell, b/c the first one listed now didn't have a date - but I'll add that after your PR). Please move it up to the top of the 2022 list. :)

**Review by staceypotter — APPROVED** [review]
LGTM, thanks!

**Review by staceypotter — APPROVED** [review]
LGTM

**Comment by VanessaWeaveworksK8S** [comment]
Thank you

**Comment by dholbach** [comment]
It appears, this was added in a different PR already:
https://github.com/fluxcd/website/blob/1c5f7e16d0bfd2adbf9c1af97503ab8868e53056/content/en/resources.yaml#L76

**Pull request closed without merging**
