### PR TITLE
fixing the hidden device problem and adjusting the scroll speed

### PR DESCRIPTION
**Pull request by h20220025**
Signed-off-by: h20220025  <h20220025@goa.bits-pilani.ac.in>

### CODE REVIEW

**Comment by h20220025** [comment]
Hey @dholbach  above is my PR can u review it:)

**Comment by kingdonb** [comment]
@h20220025 Please take a look at the DCO check

Can you sign-off your commit? per the instructions (in the details of why that check failed)

I found your reference in another PR, you can make this traceable by making a reference – right now it's not clear from the description of this PR what issue it solves. This will make the job of reviewer much easier!

Thank you for the contribution! (I will click the back button and find the post I'm talking about to link it back here, so we can make the context clearer for the next review)

**Comment by kingdonb** [comment]
Another trick, for first-time website contributor (:tada:)

If you edit the body of your PR description (top post) and put in the top line of the text "Fix #1314"

Then GitHub will automatically close that issue when your PR is finished and merged

I'll go have a look at the content now, and see if it looks like a solved thing to me 🏅

**Comment by kingdonb** [comment]
I can't merge this in its current state because of the DCO check, but I'll approve it so the next reviewer can merge!

It looks like the issue that was identified in #1154 was fixed here. 💯 🥇

**Review by kingdonb — APPROVED** [review]
LGTM 👍

**Comment by dholbach** [comment]
Can you please sign your commits?

```

**Comment by h20220025** [comment]
@dholbach  @kingdonb ts done now you can check it:)

**Comment by h20220025** [comment]
@dholbach , @kingdonb , I have signed the commits and fixed the DCOs check. Could you please review this for merging?

**Comment by h20220025** [comment]
@Arhell Could you please review the PR ?

**Comment by Arhell** [comment]
@h20220025 Thanks for the contributing

Please sync fork there are changes

To fix this error just remove this https://github.com/fluxcd/website/blob/main/assets/scss/_adopters.scss#L26.

The rest of the code is optional.

**Review by Arhell — COMMENTED** [review]
@h20220025 Thanks for the contributing

Please sync fork there are changes

To fix this error just remove this https://github.com/fluxcd/website/blob/main/assets/scss/_adopters.scss#L26.

The rest of the code is optional.

**Comment by h20220025** [comment]
@Arhell, I have synced the fork please review the PR.

**Comment by Arhell** [comment]
> 

Thanks, but anyway, I think it's better to use the property that I described above to fix the error, other styles are redundant

**Comment by h20220025** [comment]
@Arhell , I have made the changes you asked for, could you please review the PR.

**Comment by Arhell** [comment]
Tell me why additional styles for animation?
This PR needs only this
remove
```
@include media-breakpoint-down(xs) {
    display: none;
  }
```

**Comment by h20220025** [comment]
@Arhell  for adjusting the scroll speed coz when i run this with previous settings the scroll is showing nothing for 3 secs and then the logo starts scrolling so according to the width i adjusted the speed

**Comment by Arhell** [comment]
> @Arhell for adjusting the scroll speed coz when i run this with previous settings the scroll is showing nothing for 3 secs and then the logo starts scrolling so according to the width i adjusted the speed for mobile devices

Understood thanks 
lgtm @dholbach

**Pull request merged**
