### PR TITLE
Notice bar responsive sizing fixup

### PR DESCRIPTION
**Pull request by juozasg**
Fixes this and cleans up the navbar template

Screenshot from 2021-09-09 20-51-47

### CODE REVIEW

**Comment by dholbach** [comment]
Thanks a lot for the fix @juozasg - this looks great and generally much improved.

I noticed that as part of the navbar template cleanup, the indentation of a couple of lines changed. While this might look better in an editor, we might want to keep the diff between the docsy upstream navbar template and our version minimal.

This might give you an idea what I mean:

```cli
diff -u {themes/docsy/,}layouts/partials/navbar.html
```

The reason is that whenever we update our version of `docsy`, I check what changes need to be made to 1) maintain our version of the overrides, but 2) still benefit from upstream changes.

So my ask would be that you check if we can make the diff between the two a bit smaller if possible.

**Comment by juozasg** [comment]
@dholbach I'm not sure how to correctly make that change, because I moved some code from inside an `<li>`  block in the docsy template to the outside context before that `<li>` block. Then I changed the indentation to match what was already used for that context level, following the convention that new HTML context elements increase indentation, while new Hugo elements don't.  

I could make a commit that indents Hugo elements to where they were before by making Hugo `{{ range }}` indent its children, but that changes indentation logic of HTML and Hugo elements to something different from original template. If I did that I don't think this will make it easier to merge upstream changes to the navbar, since it will have a different indentation convention and will still have logical changes that I made. I could make a PR for docsy? In that case I should keep the most conventional indentation. I could also restore the original navbar logic and use styles to make the empty navbar `<li>` have 0px width. What do you think?

**Comment by dholbach** [comment]
Applying the following diff

```diff
diff --git a/layouts/partials/navbar.html b/layouts/partials/navbar.html
index 30379f7..026620e 100644
--- a/layouts/partials/navbar.html
+++ b/layouts/partials/navbar.html
@@ -5,17 +5,15 @@
        </a>
                <ul class="navbar-nav mt-2 mt-lg-0">
                        {{ $p := . }}
-
                        {{ range .Site.Menus.main }}
-
-                       {{ $active := or ($p.IsMenuCurrent "main" .) ($p.HasMenuCurrent "main" .) }}
-                       {{ with .Page }}
-                       {{ $active = or $active ( $.IsDescendant .)  }}
-                       {{ end }}
-                       {{ $pre := .Pre }}
-                       {{ $post := .Post }}
-                       {{ $url := urls.Parse .URL }}
-                       {{ $baseurl := urls.Parse $.Site.Params.Baseurl }}
+                               {{ $active := or ($p.IsMenuCurrent "main" .) ($p.HasMenuCurrent "main" .) }}
+                               {{ with .Page }}
+                               {{ $active = or $active ( $.IsDescendant .)  }}
+                               {{ end }}
+                               {{ $pre := .Pre }}
+                               {{ $post := .Post }}
+                               {{ $url := urls.Parse .URL }}
+                               {{ $baseurl := urls.Parse $.Site.Params.Baseurl }}
 
                        {{ if .HasChildren }}
 
@@ -39,7 +37,16 @@
 
                        {{ end }}
                        {{ end }}
-
+                       {{ if  .Site.Params.versions }}
+                       <li class="nav-item dropdown mr-4 d-none d-lg-block">
+                               {{ partial "navbar-version-selector.html" . }}
+                       </li>
+                       {{ end }}
+                       {{ if  (gt (len .Site.Home.Translations) 0) }}
+                       <li class="nav-item dropdown mr-4 d-none d-lg-block">
+                               {{ partial "navbar-lang-selector.html" . }}
+                       </li>
+                       {{ end }}
                        <li class="nav-item nav-search-item">{{ partial "search-input.html" . }}</li>
                </ul>
 </nav>

```

I get this:

```cli
website on  notice-bar-responsive-sizing-fixup [$!] via  v14.17.6 via 🐍 v3.8.10 
❯ diff -u {themes/docsy/,}layouts/partials/navbar.html
--- themes/docsy/layouts/partials/navbar.html	2021-07-20 18:13:59.000000000 +0200
+++ layouts/partials/navbar.html	2021-09-10 10:57:54.840357933 +0200
@@ -3,11 +3,9 @@
         <a class="navbar-brand" href="{{ .Site.Home.RelPermalink }}">
 		<span class="navbar-logo">{{ if .Site.Params.ui.navbar_logo }}{{ with resources.Get "icons/logo.svg" }}{{ ( . | minify).Content | safeHTML }}{{ end }}{{ end }}</span><span class="text-uppercase font-weight-bold">{{ .Site.Title }}</span>
 	</a>
-	<div class="td-navbar-nav-scroll ml-md-auto" id="main_navbar">
 		<ul class="navbar-nav mt-2 mt-lg-0">
 			{{ $p := . }}
 			{{ range .Site.Menus.main }}
-			<li class="nav-item mr-4 mb-2 mb-lg-0">
 				{{ $active := or ($p.IsMenuCurrent "main" .) ($p.HasMenuCurrent "main" .) }}
 				{{ with .Page }}
 				{{ $active = or $active ( $.IsDescendant .)  }}
@@ -16,8 +14,28 @@
 				{{ $post := .Post }}
 				{{ $url := urls.Parse .URL }}
 				{{ $baseurl := urls.Parse $.Site.Params.Baseurl }}
+
+			{{ if .HasChildren }}
+
+			<li class="nav-item dropdown">
+				<a class="nav-link {{if $active }} active{{end}} dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
+					{{ .Name }}
+				</a>
+				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
+				{{ range .Children  }}
+					{{ $childrenurl := urls.Parse .URL }}
+					<a class="dropdown-item" href="{{ with .Page }}{{ .RelPermalink }}{{ else }}{{ .URL | relLangURL }}{{ end }}" {{ if ne $childrenurl.Host $baseurl.Host }}target="_blank" {{ end }}>{{ .Name }}</a>
+				{{ end }}
+				</div>
+			</li>
+
+			{{ else }}
+
+			<li class="nav-item mr-4 mb-2 mb-lg-0">
 				<a class="nav-link{{if $active }} active{{end}}" href="{{ with .Page }}{{ .RelPermalink }}{{ else }}{{ .URL | relLangURL }}{{ end }}" {{ if ne $url.Host $baseurl.Host }}target="_blank" {{ end }}>{{ with .Pre}}{{ $pre }}{{ end }}<span{{if $active }} class="active"{{end}}>{{ .Name }}</span>{{ with .Post}}{{ $post }}{{ end }}</a>
 			</li>
+
+			{{ end }}
 			{{ end }}
 			{{ if  .Site.Params.versions }}
 			<li class="nav-item dropdown mr-4 d-none d-lg-block">
@@ -29,7 +47,6 @@
 				{{ partial "navbar-lang-selector.html" . }}
 			</li>
 			{{ end }}
+			<li class="nav-item nav-search-item">{{ partial "search-input.html" . }}</li>
 		</ul>
-	</div>
-	<div class="navbar-nav d-none d-lg-block">{{ partial "search-input.html" . }}</div>
 </nav>

website on  notice-bar-responsive-sizing-fixup [$!] via  v14.17.6 via 🐍 v3.8.10 
❯ 

```

What do you think?

**Comment by dholbach** [comment]
And sure, if there's upstream fixes to be made, that'd be great as well. <3

The indentation is not a huge priority, but just a bit of a hassle whenever you do a three-way-merge when updating the theme.

**Comment by juozasg** [comment]
I pushed a commit with your suggested diff. I think it will be as simple as it can be for now. Thanks for the background info and please review that it is correct.

**Review by dholbach — APPROVED** [review]
thanks a lot for your attention to detail and fixing this issues!

**Pull request merged**
