### PR TITLE
Update docsy to c36be07b2dcb9aa5aa01bad6ed0f8e111dd0452c

### PR DESCRIPTION
**Pull request by dholbach**
Also minimise diff between our layouts/partial overrides.

This was a little time-consuming, but this time worth it. The sidebar looks much nicer now.

Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
Check out the foldable sidebar on https://deploy-preview-365--fluxcd.netlify.app/docs/ - wdyt?

**Comment by hiddeco** [comment]
Think the `.td-sidebar-nav .td-sidebar-link.tree-root` needs a bit more top padding so that it isn't directly linked to the top navbar.

**Comment by dholbach** [comment]
Here's our current diff regarding upstream:

```cli
❯ for f in $(git diff upstream/main HEAD | diffstat  | grep layouts | cut -d' ' -f2); do diff -u {themes/docsy/,}$f; done
--- themes/docsy/layouts/docs/baseof.html	2021-06-23 14:39:19.000000000 +0200
+++ layouts/docs/baseof.html	2021-06-29 15:55:27.542144402 +0200
@@ -13,14 +13,21 @@
           <aside class="col-12 col-md-3 col-xl-2 td-sidebar d-print-none">
             {{ partial "sidebar.html" . }}
           </aside>
+          {{ if not .Params.hugeTable }}
           <aside class="d-none d-xl-block col-xl-2 td-sidebar-toc d-print-none">
             {{ partial "page-meta-links.html" . }}
             {{ partial "toc.html" . }}
             {{ partial "taxonomy_terms_clouds.html" . }}
           </aside>
+          {{ end }}
+          {{ if not .Params.hugeTable }}
           <main class="col-12 col-md-9 col-xl-8 pl-md-5" role="main">
+          {{ else }}
+          <main class="col-12 col-md-12 col-xl-10 pl-md-5 " role="main">
+          {{ end }}
             {{ partial "version-banner.html" . }}
             {{ if not .Site.Params.ui.breadcrumb_disable }}{{ partial "breadcrumb.html" . }}{{ end }}
+            {{ if in .Permalink "/legacy" }}{{ partial "docs/legacy-warning.html" }}{{ end }}
             {{ block "main" . }}{{ end }}
           </main>
         </div>
--- themes/docsy/layouts/partials/navbar.html	2021-06-23 14:39:19.000000000 +0200
+++ layouts/partials/navbar.html	2021-06-29 15:47:59.364575463 +0200
@@ -3,7 +3,6 @@
         <a class="navbar-brand" href="{{ .Site.Home.RelPermalink }}">
 		<span class="navbar-logo">{{ if .Site.Params.ui.navbar_logo }}{{ with resources.Get "icons/logo.svg" }}{{ ( . | minify).Content | safeHTML }}{{ end }}{{ end }}</span><span class="text-uppercase font-weight-bold">{{ .Site.Title }}</span>
 	</a>
-	<div class="td-navbar-nav-scroll ml-md-auto" id="main_navbar">
 		<ul class="navbar-nav mt-2 mt-lg-0">
 			{{ $p := . }}
 			{{ range .Site.Menus.main }}
@@ -16,7 +15,21 @@
 				{{ $post := .Post }}
 				{{ $url := urls.Parse .URL }}
 				{{ $baseurl := urls.Parse $.Site.Params.Baseurl }}
+				{{ if .HasChildren }}
+				<li class="nav-item dropdown">
+					<a class="nav-link {{if $active }} active{{end}} dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
+						{{ .Name }}
+					</a>
+					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
+					{{ range .Children  }}
+						{{ $childrenurl := urls.Parse .URL }}
+						<a class="dropdown-item" href="{{ with .Page }}{{ .RelPermalink }}{{ else }}{{ .URL | relLangURL }}{{ end }}" {{ if ne $childrenurl.Host $baseurl.Host }}target="_blank" {{ end }}>{{ .Name }}</a>
+					{{ end }}
+					</div>
+				</li>
+				{{ else }}
 				<a class="nav-link{{if $active }} active{{end}}" href="{{ with .Page }}{{ .RelPermalink }}{{ else }}{{ .URL | relLangURL }}{{ end }}" {{ if ne $url.Host $baseurl.Host }}target="_blank" {{ end }}>{{ with .Pre}}{{ $pre }}{{ end }}<span{{if $active }} class="active"{{end}}>{{ .Name }}</span>{{ with .Post}}{{ $post }}{{ end }}</a>
+				{{ end }}
 			</li>
 			{{ end }}
 			{{ if  .Site.Params.versions }}
@@ -25,11 +38,10 @@
 			</li>
 			{{ end }}
 			{{ if  (gt (len .Site.Home.Translations) 0) }}
-			<li class="nav-item dropdown d-none d-lg-block">
+			<li class="nav-item dropdown d-lg-block">
 				{{ partial "navbar-lang-selector.html" . }}
 			</li>
 			{{ end }}
+			<li class="nav-item nav-search-item">{{ partial "search-input.html" . }}</li>
 		</ul>
-	</div>
-	<div class="navbar-nav d-none d-lg-block">{{ partial "search-input.html" . }}</div>
 </nav>
--- themes/docsy/layouts/partials/page-meta-links.html	2021-06-23 14:39:19.000000000 +0200
+++ layouts/partials/page-meta-links.html	2021-06-29 15:42:05.436221709 +0200
@@ -5,6 +5,7 @@
   {{ $gh_subdir := ($.Param "github_subdir") }}
   {{ $gh_project_repo := ($.Param "github_project_repo") }}
   {{ $gh_branch := (default "master" ($.Param "github_branch")) }}
+  {{ $importedDoc := $.Param "importedDoc" | default "false" }}
   <div class="td-page-meta ml-2 pb-1 pt-2 mb-0">
   {{ if $gh_url }}
      <a href="{{ $gh_url }}" target="_blank"><i class="fa fa-edit fa-fw"></i> {{ T "post_edit_this" }}</a>     
@@ -24,8 +25,10 @@
     {{ $newPageQS := querify "value" $newPageStub.Content "filename" "change-me.md" | safeURL }}
     {{ $newPageURL := printf "%s/new/%s?%s"  $gh_repo $gh_repo_path $newPageQS }}
 
+    {{ if eq $importedDoc "false" }}
     <a href="{{ $editURL }}" target="_blank"><i class="fa fa-edit fa-fw"></i> {{ T "post_edit_this" }}</a>
     <a href="{{ $newPageURL }}" target="_blank"><i class="fa fa-edit fa-fw"></i> {{ T "post_create_child_page" }}</a>
+    {{ end }}
     <a href="{{ $issuesURL }}" target="_blank"><i class="fab fa-github fa-fw"></i> {{ T "post_create_issue" }}</a>
     {{ if $gh_project_repo }}
       {{ $project_issueURL := printf "%s/issues/new" $gh_project_repo }}
--- themes/docsy/layouts/partials/sidebar-tree.html	2021-06-23 14:39:19.000000000 +0200
+++ layouts/partials/sidebar-tree.html	2021-06-29 15:51:25.127108409 +0200
@@ -11,7 +11,6 @@
   {{ else }}
   <div id="content-mobile">
   <form class="td-sidebar__search d-flex align-items-center">
-    {{ partial "search-input.html" . }}
     <button class="btn btn-link td-sidebar__toggle d-md-none p-0 ml-3 fas fa-bars" type="button" data-toggle="collapse" data-target="#td-section-nav" aria-controls="td-docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
     </button>
   </form>
```

**Comment by dholbach** [comment]
> Think the `.td-sidebar-nav .td-sidebar-link.tree-root` needs a bit more top padding so that it isn't directly linked to the top navbar.

What's a good way of doing this? I'm wondering if we override this somewhere...

**Comment by hiddeco** [comment]
@dholbach please remind me within 48h (from tomorrow on) if I haven't given a suggestion. I am sure @stefanprodan will be very happy with this sidebar change.

**Comment by stefanprodan** [comment]
Can we fix the first 2 items so that they don't look disabled? Sidebar looks great, thanks Daniel.

**Comment by dholbach** [comment]
I can't quite make sense of why this is -will take another look tomorrow.

**Comment by hiddeco** [comment]
Seems to be because the pages are classified differently.

- Get started: `align-left pl-0 td-sidebar-link td-sidebar-link__page`
- Installation: `align-left pl-0 td-sidebar-link td-sidebar-link__section`

Spacing of the top menu title seems to be fixed by adding `margin-top: 1rem` to `.td-sidebar-nav .td-sidebar-link.tree-root`, but should only be done for non-mobile view ports as otherwise the mobile navigation is affected.

**Comment by dholbach** [comment]
> Seems to be because the pages are classified differently.
> 
>     * Get started: `align-left pl-0 td-sidebar-link td-sidebar-link__page`
> 
>     * Installation: `align-left pl-0 td-sidebar-link td-sidebar-link__section`

This was due to us having empty sections, e.g. just `installation/_index.md` (instead of `installation.md`. I fixed this.

**Comment by dholbach** [comment]
> Spacing of the top menu title seems to be fixed by adding `margin-top: 1rem` to `.td-sidebar-nav .td-sidebar-link.tree-root`, but should only be done for non-mobile view ports as otherwise the mobile navigation is affected.

Fixed too.

**Comment by hiddeco** [comment]
> This was due to us having empty sections, e.g. just `installation/_index.md` (instead of `installation.md`. I fixed this.

Interesting this is that the section one looked better (and less "disabled") than the page version. :grimacing: 

> Fixed too.

Looks pretty on mobile / tablet / desktop as far as I can see not, great job!

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @dholbach 🏅

**Comment by dholbach** [comment]
Let me have another look at the disabled colours.

**Comment by hiddeco** [comment]
Think that overwriting `.td-sidebar-nav .td-sidebar-link__page` with `color: #222` should do the job.

**Comment by dholbach** [comment]
:heavy_check_mark:

**Pull request merged**
