### PR TITLE
Trim landing page by merging sections

### PR DESCRIPTION
**Pull request by dholbach**
- First step: move community and adoption text to other relevant sections
- Move shortcodes pertaining to home page into their own directory
- Re-style features section

Fixes: #1327

### CODE REVIEW

**Comment by dholbach** [comment]
I draw some inspiration regarding how to structure the features section from fission.io - what do you think? The idea would be to merge the content from "gitops at your fingertips" and "flux in short" sections into a features section - or maybe a benefits and features? 

grafik

**Comment by dholbach** [comment]
The colour of the icons is a bit in-your-face, but I was looking for something a little friendlier than the current quite dark blue, and used a colour of part of what's to see in the CNCF chasm diagram at the top of the current landing page.

**Comment by dholbach** [comment]
→ https://deploy-preview-1385--fluxcd.netlify.app/

**Comment by hiddeco** [comment]
Why do we not just use another shade of blue? Introduction of purple to the otherwise purple-less color scheme looks a bit out-of-place imho.

**Comment by dholbach** [comment]
> Why do we not just use another shade of blue? Introduction of purple to the otherwise purple-less color scheme looks a bit out-of-place imho.

Sure, I'm happy to do that - do you have a suggestion?

**Comment by hiddeco** [comment]
Just the same color as primary (`#3d6ddd`)?

image

**Comment by dholbach** [comment]
grafik


From left to right: this PR, current website, previously before we started work on #1327

**Comment by dholbach** [comment]
Please ignore the (unrelated) big calendar section in the screenshot, I filed #1392 for this.

**Pull request merged**
