### PR TITLE
Add FluxCD Azure DevOps article resource

### PR DESCRIPTION
**Pull request by kingdonb**
Testing the Resources / Article feature again. (also #2096)

Thanks Mohammed Nour for contributing this article about the new features in Flux 2.4 🎉 

(I asked if there was a branding image that goes with this blog, and it was suggested we just use the Flux logo as there isn't one.)

### CODE REVIEW

**Comment by kingdonb** [comment]
https://deploy-preview-2097--fluxcd.netlify.app/resources/

I think we should add a bit of description, since there is a place for it in the "article" format and the Flux logo doesn't fill the same 4x3 space as the others. Running this by the author to see what text we can put in there before we publish this.

**Comment by stefanprodan** [comment]
The article is about migrating existing clusters from Azure PAT or SSH to OIDC. I think the title should say this.

**Comment by kingdonb** [comment]
> In this article, I’ll guide you step-by-step through the process of setting up Flux source-controller and image-automation-controller to authenticate against Azure DevOps repositories using OIDC tokens

This sentence from the article I picked is probably too long for the description, and doesn't say exactly what you just said... but combining them, might be the right level of detail - how about this (let's see if it fits in the box):

> Migrating existing cluster Git sources and image automations from Azure PAT or SSH to OIDC

**Comment by stefanprodan** [comment]
Maybe "Migrating AKS clusters to Azure DevOps OIDC-based auth"

**Comment by kingdonb** [comment]
This LGTM

**Comment by kingdonb** [comment]
Maybe better if it wasn't center-aligned, I'll tweak it...

**Comment by kingdonb** [comment]
Did several iterations on the CSS and template for description in resources, I think this is better 👍

**Comment by kingdonb** [comment]
Screenshot 2024-11-25 at 3 21 52 PM

Preview ^

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @kingdonb 🥇

**Pull request merged**
