### PR TITLE
Update code block on mobile

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/fluxcd/website/issues/995

### CODE REVIEW

**Comment by Arhell** [comment]
cc @dholbach

**Comment by dholbach** [comment]
Thanks @Arhell this is much better!

Do you think it'd make sense to make the overflow scrollbar visible in those case so it's easier to understand that there's content you can't see in that moment? Looks like Firefox and Chrome both don't show it for me in mobile view with more content in the codeblocks.

**Comment by Arhell** [comment]
> Thanks @Arhell this is much better!
> 
> Do you think it'd make sense to make the overflow scrollbar visible in those case so it's easier to understand that there's content you can't see in that moment? Looks like Firefox and Chrome both don't show it for me in mobile view with more content in the codeblocks.

There is an attribute with a scrolling.
This is a feature of the browser on a mobile device.

I looked at examples on different sites, everything is the same there.

**Review by dholbach — APPROVED** [review]
Thanks for resolving this.

It looks the problem started appearing recently when https://github.com/google/docsy/blame/main/assets/scss/_code.scss#L6 behaviour was changed through https://github.com/google/docsy/commit/1731334ab7c402133eed28920336c35af04febbd#diff-1f4d7b8618cd04fd8c5bf1b1dc08c5ae99ade3e2418c79d1e8f2acaa07a90923R5

**Pull request merged**
