### PR TITLE
Add golang to hugo-support image

### PR DESCRIPTION
**Pull request by kingdonb**
We've had this docker serve stuff in the Makefile and it has been broken since some time ago, I am working it out in this branch.

### CODE REVIEW

**Comment by kingdonb** [comment]
I was able to build and run the environment locally again with these changes. The docs did not appear to need any updates just now, but the runtime environment apparently requires Go now (or will soon) which I added in the support image.

**Review by makkes — COMMENTED** [review]
This lgtm but I'm leaning towards putting the changes to the Makefile into #1577 because without any context it's not easily understandable why the `BRANCH` variable is introduced here. wdyt?

**Comment by kingdonb** [comment]
Yes, I'll pull them out from this branch so we can merge it, (the commit id was 1aaf55f so we do not lose track)

**Comment by kingdonb** [comment]
Should be in shape for merge 👍

**Review by makkes — APPROVED** [review]

**Pull request merged**
