### PR TITLE
Add DataDog integration for Flux2

### PR DESCRIPTION
**Pull request by Santosh1176**
Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>

Adds DataDog integrations to the integration section of the Ecosystem page.

DataDog

@dholbach suggestions welcome.

### CODE REVIEW

**Review by dholbach — COMMENTED** [review]
This looks great.
Do you think you can sort the entries alphabetically and add a newline at the end?

**Comment by Santosh1176** [comment]
>  sort the entries alphabetically and add a newline at the end

Is this what you were looking for?

integrations1

**Comment by dholbach** [comment]
> Is this what you are looking for?

yes, super

**Review by dholbach — APPROVED** [review]
Thanks s lot!

**Pull request merged**
