### PR TITLE
Add integrations page

### PR DESCRIPTION
**Pull request by dholbach**
Fixes: #302

### CODE REVIEW

**Comment by dholbach** [comment]
https://deploy-preview-342--fluxcd.netlify.app/integrations/ is generated from https://github.com/dholbach/website/blame/fix-302/content/en/integrations.md - WDYT? Icons are somewhat bigger than on the adopters page.

All info is from the GitHub pages of the specific tools and integrations.

**Comment by dholbach** [comment]
Paging some of the top contributors for the integrations to make sure you're all right with the additions:

- kraan: @paulcarlton-ww @wangli1030
- bedrock: @timfpark @jmspring
- fabrikate: @evanlouie @edaena 
- gitops-connector: @eedorenko @tcare 
- jsonnect-controller: @tinyzimmer
- das-schiff: @vukg @maxrink
- weave-gitops: @j-thompson12 @jrryjcksn

**Comment by stefanprodan** [comment]
@dholbach we need to split these into 2 categories:
- Flux extensions
- Flux integrations

From the current list only the jsonnet-controller can be considered an extension to Flux as it uses the GitOps Toolkit SDK.

**Comment by dholbach** [comment]
@stefanprodan Can both categories still be at the same URL?

**Comment by stefanprodan** [comment]
yes

**Comment by dholbach** [comment]
Ok, your request is sorted now, @stefanprodan - thanks!

**Review by scottrigby — APPROVED** [review]
This looks great @dholbach! 👏 👏 

Before merging this, do you want to add "fixes #302" to the issue description?
More for fun 😄 https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by dholbach** [comment]
If any of the folks above feel like we could better present your integration or extension (or you want it removed for some reason), please speak up on this PR and I'll take care ofit.

**Comment by stefanprodan** [comment]
I doubt Microsoft and DT will agree to this, they are not even on the Adaption page...

**Pull request merged**
