### PR TITLE
ui update on mobile (hero block)

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/fluxcd/website/issues/874

### CODE REVIEW

**Comment by Arhell** [comment]
after update
Screenshot_1

**Comment by Arhell** [comment]
cc @dholbach

**Comment by stefanprodan** [comment]
Looks good on iPhone! Thanks @Arhell  

10B8E0AF-ECC2-483E-A24B-5084F551AD5C

PS. We need to figure out how to collapse  the menu items on mobile and display only one row in the top menu, but that’s for another PR.

**Review by stefanprodan — APPROVED** [review]

**Comment by Arhell** [comment]
> PS. We need to figure out how to collapse the menu items on mobile and display only one row in the top menu, but that’s for another PR.

Yes, this is also in my plans for working on this site

**Comment by dholbach** [comment]
Thanks @Arhell

**Pull request merged**
