### PR TITLE
Update helm.md

### PR DESCRIPTION
**Pull request by qingvincentyin**

### CODE REVIEW

**Comment by dholbach** [comment]
Thanks for the PR!

Do you think you can run

```sh
git commit --amend --no-edit --signoff
git push --force-with-lease origin patch-1
```

or use https://github.com/scottrigby/dco-gh-ui to submit this?

**Comment by qingvincentyin** [comment]
OK. I did this from my laptop:

➜  ~ $ git clone ***@***.******@***.***>:qingvincentyin/website.git
…

➜  ~ $ cd website

➜  website git:(main) $ git checkout patch-1

➜  website git:(patch-1) $ git commit --amend --no-edit --signoff
[patch-1 0627cce] Update helm.md
 Author: Vincent Yin ***@***.******@***.***>>
 Date: Mon Jul 19 00:16:35 2021 -0400
 1 file changed, 1 insertion(+), 1 deletion(-)


➜  website git:(patch-1) $ git push --force-with-lease origin patch-1
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 12 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 563 bytes | 563.00 KiB/s, done.
Total 7 (delta 5), reused 1 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To github.com<http://github.com>:qingvincentyin/website.git
 + 7724d22...0627cce patch-1 -> patch-1 (forced update)



Then followed by this:

[cid:A7A35B65-6705-4237-90A1-8B27A2A8D162]




…which resulted in this:


[cid:D91476B0-ED95-4750-A5C7-209B6FB2AD03]



On Jul 19, 2021, at 5:08 AM, Daniel Holbach ***@***.******@***.***>> wrote:


git push --force-with-lease origin patch-1

**Comment by dholbach** [comment]
#313 fixes this similarly?

**Comment by qingvincentyin** [comment]
> #313 fixes this similarly?

#313 doesn't cover all the bugs I found. It missed the `--target-namespace` bug which my PR found.
I suppose a combination of the two should do.

**Comment by scottrigby** [comment]
Hi @qingvincentyin, We appreciate all contributions and thank you for this PR!

However I am not so sure about this:

> > #313 fixes this similarly?
> 
> #313 doesn't cover all the bugs I found. It missed the `--target-namespace` bug which my PR found.
> I suppose a combination of the two should do.

Can you please describe the bug you're running into in detail, and why this would be a fix?

My understanding is `--target-namespace` installs the helm-managed resources into a different namespace than the release metadata. That is intended for use cases where you specifically want this non-standard behavior, as one of several access control strategies.

By contrast, the update in #313 seems to work just fine, and retains standard helm release behavior (`helm ls -A` etc continues to work as expected):

```console
$ flux create source helm traefik --url https://helm.traefik.io/traefik --namespace traefik
✚ generating HelmRepository source
► applying HelmRepository source
:heavy_check_mark: source created
◎ waiting for HelmRepository source reconciliation
:heavy_check_mark: HelmRepository source reconciliation completed
:heavy_check_mark: fetched revision: 44a296d4b291f5ffd399a3a4a889fb2781343304
$ flux create helmrelease my-traefik --chart traefik \
>   --source HelmRepository/traefik \
>   --chart-version 9.18.2 \
>   --namespace traefik
✚ generating HelmRelease
► applying HelmRelease
:heavy_check_mark: HelmRelease created
◎ waiting for HelmRelease reconciliation
:heavy_check_mark: HelmRelease my-traefik is ready
:heavy_check_mark: applied revision 9.18.2
$ kubectl get pods -A | grep traefik
traefik         my-traefik-5d4c45d56b-cl7wq                 1/1     Running   0          39s
```

Thanks again. Please help us better understand, and when appropriate will be very happy to add your contribution to the docs!

**Comment by qingvincentyin** [comment]
Running the exact commands in your above comment would result in what you demonstrated, and all will be good. However, your first command is (verbatim):
```console
$ flux create source helm traefik --url https://helm.traefik.io/traefik --namespace traefik
```

That's not the exact command in the published [helm.md](https://fluxcd.io/docs/use-cases/helm/). Rather, your command has an extra `--namespace traefik`, and that made all the difference (for your run). At the end of your run, you'd get:
```console
$ kubectl get hr -A
NAMESPACE   NAME.          READY   STATUS                             AGE
traefik     my-traefik     True    Release reconciliation succeeded   ...

$ helm list -A
NAME        NAMESPACE	...	STATUS  	CHART
my-traefik  traefik  	...	deployed	traefik-9.18.2

$ k get pods -A | grep traefik
traefik     my-traefik-67cc689c8d-gw4x2     1/1     Running   ...
```

All the above 3 sets of objects are in `traefik` namespace. Everything is working.

Had you omitted the `--namespace traefik` on the command line of `flux create source helm ...`, you'd likely get the following timeout error, and no Helm Release and no app is deployed (this is what happened to me):
```console
$ flux create source helm traefik --url https://helm.traefik.io/traefik
✚ generating HelmRepository source
► applying HelmRepository source
✔ source created
◎ waiting for HelmRepository source reconciliation
✔ HelmRepository source reconciliation completed
✔ fetched revision: 44a296d4b291f5ffd399a3a4a889fb2781343304

$ flux create helmrelease my-traefik --chart traefik --source HelmRepository/traefik --chart-version 9.18.2 --namespace traefik
✚ generating HelmRelease
► applying HelmRelease
✔ HelmRelease created
◎ waiting for HelmRelease reconciliation
✗ context deadline exceeded                       <<====== Timeout error

$ kubectl get hr -A
NAMESPACE   NAME         READY   STATUS                                                AGE
traefik     my-traefik   False   HelmChart 'traefik/traefik-my-traefik' is not ready   7m16s

$ helm list -A
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
$    ### ... Outputs nothing

$ kubectl get pods -A | grep traefik
$    ### ... Outputs nothing
```

One way to overcome the above error is to do what you did; another way is to do what I am proposing in this PR, i.e., add `--target-namespace traefik`. Which way to go depends on which namespace you'd like the Flux `hr` metadata to reside in -- now I think of it, maybe your way is more preferable. Regardless, something needs to give; the current published [helm.md](https://fluxcd.io/docs/use-cases/helm/) won't work (and #313 doesn't solve the problem in this regard).

**Comment by scottrigby** [comment]
@qingvincentyin thanks I actually missed that 👓 in this doc. Yes you are right, the `flux create source` command is missing `traefik` namespace. Yes it's correct you could solve this in one of those two ways. I believe we should default users to the expected helm functionality (chart metadata and controlled resources in the same namespace), therefore we should add namespace to that command as well. I also agree it would be good to make this relationship more clear.

**Comment by qingvincentyin** [comment]
OK. I'll change my code to do the `namespace` your way. My `fork` says that:
> This branch is 50 commits behind the upstream and has conflicts that must be resolved.
Open a pull request to fetch upstream and review changes or resolve conflicts.

So, this branch (and this PR) is now too out of sync. Maybe there's a way to salvage it, but my simple attempt didn't work (there's a merge conflict and I don't have `write access` to resolve the conflict) and I'm not a Git expert for this scenario. So, given that this is a tiny change, I've just opened a new PR #442 (based on the latest `main` branch).

I suppose you can close this PR and accept the new PR.

**Comment by dholbach** [comment]
Thanks a lot @qingvincentyin for your attention to detail - closing this PR in favour of #442.

**Pull request closed without merging**
