### PR TITLE
Add Ænix to adopters

### PR DESCRIPTION
**Pull request by gecube**

### CODE REVIEW

**Review by makkes — APPROVED** [review]
🥳

**Comment by stefanprodan** [comment]
@gecube could you please rebase, thanks!

**Comment by gecube** [comment]
@stefanprodan done, thanks for the attention

**Comment by kingdonb** [comment]
Ænix was already added to the adopters list earlier this year, about 8 entries back!

**Comment by gecube** [comment]
@kingdonb my bad .... I have a memory like guppy fish :-(

**Comment by kingdonb** [comment]
It's ok, I am excited about Cozystack too, easy mistake to make!

**Pull request merged**
