### PR TITLE
Adding GitOpsCon videos to resources section

### PR DESCRIPTION
**Pull request by Santosh1176**
Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>

This PR resolves [issue #953](https://github.com/fluxcd/website/issues/953#issue-1244722958) by adding GitOpsCon 2022 video playlist to the Resources section.

### CODE REVIEW

**Comment by staceypotter** [comment]
Question for you @Santosh1176: is this the entire GitOpsCon EU 2022 playlist? If so, I don't think we want to include the entire thing, but just videos that are centered on Flux instead. 

I created a playlist called [Flux at GitOpsCon, KubeCon, CloudNativeCon EU 2022](https://youtube.com/playlist?list=PLwjBY07V76p53FP85y03psCnb95u095Do) on the [Flux YouTube channel](https://www.youtube.com/channel/UCoZxt-YMhGHb20ZkvcCc5KA) a while back, but haven't added all of the KubeCon sessions yet. However, if you just link to this playlist instead we can add those later and it will still be the same link.

**Comment by Santosh1176** [comment]
Thank you @staceypotter for catching this early. Yes, this is a full list of GitOpsCon playlist. I'll replace this with the relevant link [Flux at GitOpsCon, KubeCon, CloudNativeCon EU 2022](https://youtube.com/playlist?list=PLwjBY07V76p53FP85y03psCnb95u095Do) as suggested.

**Comment by Santosh1176** [comment]
> Thank you @staceypotter for catching this early. Yes, this is a full list of GitOpsCon playlist. I'll replace this with the relevant link [Flux at GitOpsCon, KubeCon, CloudNativeCon EU 2022](https://youtube.com/playlist?list=PLwjBY07V76p53FP85y03psCnb95u095Do) as suggested.

Done!

**Comment by staceypotter** [comment]
I would also say that all individual videos on this playlist could also be listed as separate videos on the Resources page as well (that way they have search-ability and visibility as individual sessions, not just on the playlist). Would you be able to do that as well while you're updating? LMK if you need help and I can jump on this part too. :)

**Comment by Santosh1176** [comment]
> I would also say that all individual videos on this playlist could also be listed as separate videos on the Resources page as well (that way they have search-ability and visibility as individual sessions, not just on the playlist). Would you be able to do that as well while you're updating? LMK if you need help and I can jump on this part too. :)

Sure! could you please help me with the list of videos to be added. As a newcomer, I could miss some important ones.

**Comment by staceypotter** [comment]
Absolutely! How would you prefer I list them, is here in a comment ok?

**Comment by Santosh1176** [comment]
Here or Slack will do as well. It's okay either way.

**Comment by staceypotter** [comment]
@Santosh1176 I went through the KubeCon schedule and added all the videos that mention or talk about Flux in some way shape or form, so that playlist [Flux at GitOpsCon, KubeCon, CloudNativeCon EU 2022](https://youtube.com/playlist?list=PLwjBY07V76p53FP85y03psCnb95u095Do)) is now completely up to date.

**Comment by Santosh1176** [comment]
All the 19 videos should be added and the playlist removed from the resources. Or do you suggest keeping both individual and playlist on the resources page?

**Comment by staceypotter** [comment]
> 

I do think it's a good idea to list all videos individually, but also have the playlist compilation too. I believe all of our Resources are listed chronologically (newest to oldest). And if you'd like I can list them out here in the order of appearance, if that helps?

**Comment by Santosh1176** [comment]
Yes, please, that'll help me a lot in adding the resources. The playlist shows a date range from 17-19 May-2022 but individual videos do not have the date mentioned.

**Comment by Santosh1176** [comment]
> I do think it's a good idea to list all videos individually, but also have the playlist compilation too. I believe all of our Resources are listed chronologically (newest to oldest). And if you'd like I can list them out here in the list order, if that helps?

Awaiting your update/guidance on this.

**Comment by staceypotter** [comment]
> > I do think it's a good idea to list all videos individually, but also have the playlist compilation too. I believe all of our Resources are listed chronologically (newest to oldest). And if you'd like I can list them out here in the list order, if that helps?
> 
> Awaiting your update/guidance on this.

My apologies @Santosh1176! I was on holiday the last couple of weeks and was hoping to get to this before I left, but was unable. Here's the list as I see it in chronological order (newest to oldest, with the Playlist listed first and dates commented out - I'm putting them there for referencing):

- [Playlist: Flux at GitOpsCon & KubeCon EU 2022](https://youtube.com/playlist?list=PLwjBY07V76p53FP85y03psCnb95u095Do)
- [From Student to SRE That Loves CNCF in No Time - Jacob Valdemar Andreasen, Lunar](https://www.youtube.com/watch?v=7_k8Ni7VQy0&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=20)(May 20, 2022)
- [Simplifying Service Mesh Operations with Flux and Flagger - Mitch Connors & Stefan Prodan](https://www.youtube.com/watch?v=1rJYsdLgJGA&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=19)(May 20, 2022)
- [KubeCon EU 2022: Observing Fastly’s Network at Scale Thanks to K8s and the Stri... Fernando Crespo & Daniel Caballero](https://www.youtube.com/watch?v=eYZO7n_o0OQ&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=18)(May 20, 2022)
- [KubeCon EU 2022: Flux Virtual Office Hours with Flux Maintainers](https://www.youtube.com/watch?v=BrYgx4cB7p4&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=11)(May 19, 2022)
- [KubeCon EU 2022: GitOps to Automate the Setup, Management and Extension a K8s Cluster - Kim Schlesinger, DigitalOcean](https://www.youtube.com/watch?v=rra7TkYOnko&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=17&t=23s)(May 19, 2022)
- [KubeCon EU 2022: Flux Security Deep Dive - Stefan Prodan, Weaveworks](https://www.youtube.com/watch?v=MjxZcY6THdc&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=16&t=12s)(May 18, 2022)
- [KubeCon EU 2022: Intro to Kubernetes, GitOps, and Observability Hands-On Tutorial - Joaquin Rodriguez & Tiffany Wang](https://www.youtube.com/watch?v=WKvogzTg2iM&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=15)(May 18, 2022)
- [KubeCon EU 2022: Lightning Talk: Scaling Container Builds with Software Supply Chains - Duane DeCapite, VMware](https://www.youtube.com/watch?v=BKegE2VQhnU&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=14)(May 17, 2022)
- [Flux Virtual Booth Talk: Progressive Delivery with Flagger and Gateway API by Sanskar Jaiswal](https://www.youtube.com/watch?v=pN41tIKn3eE&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=13&t=2s)
- [Flux Virtual Booth Talk: Secure Your Secrets in GitOps with Rosemary Wang](https://www.youtube.com/watch?v=6gwgG6yhN04&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=12)
- [GitOpsCon EU 2022: GitOps Everything!? We Sure Can!, Ayelet de-Roos, AppsFlyer](https://www.youtube.com/watch?v=qGQyGuoS5Ds&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=10&t=1s)(May 17, 2022)
- [GitOpsCon EU 2022: Crossing the Divide: How GitOps Brought AppDev & Platform Teams Together! - Priyanka "Pinky" Ravi](https://www.youtube.com/watch?v=0jNtDnWT3yo&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=9)(May 17, 2022)
- [GitOpsCon EU 2022: Managing Thousands of Clusters and Their Workloads with Flux - Max Jonas Werner, D2iQ](https://www.youtube.com/watch?v=Xei2ZcEg5B0&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=8)(May 17, 2022)
- [GitOpsCon EU 2022: Solving Environment Promotion with Flux - Sam Tavakoli & Adelina Simion, Form3](https://www.youtube.com/watch?v=gqs4mVppn1Q&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=7)(May 17, 2022)
- [GitOpsCon EU 2022: Lightning Talk: GitOps, A Slightly Realistic Situation on Kuberne... Laurent Grangeau & Ludovic Piot](https://www.youtube.com/watch?v=uU-zbTgbHPI&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=6&t=77s)(May 17, 2022)
- [GitOpsCon EU 2022: Creating A Landlord for Multi-tenant K8s Using Flux, Gatekeeper, Helm, and Friends - Michael Irwin](https://www.youtube.com/watch?v=agsnktpIxzU&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=5)(May 17, 2022)
- [GitOpsCon EU 2022: Lightning Talk: GitOps and Progressive Delivery with Flagger, Istio and Flux - Marco Amador, Anova](https://www.youtube.com/watch?v=AKVfqn85ZJ4&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=4)(May 17, 2022)
- [GitOpsCon EU 2022: Lightning Talk: Taming the Thundering Gitops Herd with Update... Joaquim Rocha & Iago López Galeiras](https://www.youtube.com/watch?v=20f6yYK-RWM&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=3)(May 17, 2022)
- [GitOpsCon EU 2022: Lightning Talk: Hiding in Plain Sight - How Flux Decrypts Secrets - Somtochi Onyekwere, Weaveworks](https://www.youtube.com/watch?v=2rJur5VE6yA&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=2)(May 17, 2022)
- [GitOpsCon EU 2022: We Have Always Done It This Way! Now Let’s Try Something Completely Different -Eliran Bivas](https://www.youtube.com/watch?v=es5ngkzJDEc&list=PLwjBY07V76p53FP85y03psCnb95u095Do&index=1&t=182s)(May 17, 2022)

**Comment by Santosh1176** [comment]
Thank you @staceypotter.

**Comment by Santosh1176** [comment]
> I think this is good to go. Thanks so much @Santosh1176 👍 ❤️ 

Thank you!

**Review by dholbach — APPROVED** [review]

**Pull request merged**
