### PR TITLE
add image of 'flux diff kustomization'

### PR DESCRIPTION
**Pull request by dholbach**
Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
https://deploy-preview-731--fluxcd.netlify.app/blog/ and https://deploy-preview-731--fluxcd.netlify.app/blog/2022/01/january-update/

**Comment by stefanprodan** [comment]
Use this one: Screenshot 2022-02-01 at 17 32 48

You may want to minify it first.

**Comment by dholbach** [comment]
> You may want to minify it first.

That's done during the build. 😎

**Review by stefanprodan — APPROVED** [review]
Use this one

**Pull request merged**
