### PR TITLE
Promote next event

### PR DESCRIPTION
**Pull request by dholbach**
Fixes: #1204

Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
image


Let me know if you can think of any better place. Or how this could be styled to look nicer.

**Comment by dholbach** [comment]
@Arhell WDYT? Is there a way we could highlight the "next event" on the landing page better?

**Review by Arhell — COMMENTED** [review]
I suggest increasing the padding a bit
padding-bottom: 45px;
padding-top: 20px;

and make the link have text-decoration: underline;

to highlight that this is an event

Screenshot_1

**Comment by dholbach** [comment]
Thanks for the feedback - it indeed looks a lot better!

**Comment by dholbach** [comment]
→ https://deploy-preview-1223--fluxcd.netlify.app/

**Comment by Arhell** [comment]
And maybe increase the font size?
34px I think enough

**Review by stefanprodan — APPROVED** [review]

**Pull request merged**
