### PR TITLE
Update website release instructions

### PR DESCRIPTION
**Pull request by makkes**
The instructions haven't reflected our actual procedure, anymore.

[preview](https://deploy-preview-1960--fluxcd.netlify.app/flux/releases/procedure/#distribution-minor-release-website)

### CODE REVIEW

**Comment by stefanprodan** [comment]
We need to capture the updates needed to the token here https://github.com/fluxcd/website/blob/591ae69c51e0c3eebbeead9af0aff5b18d1f1220/.github/workflows/netlify.yml#L18

**Comment by kingdonb** [comment]
I think the token does not change, based on the update in the instructions, the same token is reused and the webhook secret in github actions config should probably be named `VCURRENTMINOR` instead of the literal current minor version

**Comment by kingdonb** [comment]
this part:

> Go to https://app.netlify.com/sites/fluxcd/configuration/deploys#branches-and-deploy-contexts
> Click on “Configure”
> In “Production branch”, **change the value from v2-(N-1) to v2-N.**
> In “Additional branches” add the “v2-(N-1)” branch.

**Comment by makkes** [comment]
@stefanprodan @kingdonb I added instructions to update the "netlify" GHA workflow.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @makkes 🏅

**Pull request merged**
