### PR TITLE
Move to docsy as Hugo module

### PR DESCRIPTION
**Pull request by dholbach**
Fixes: #889

Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by stefanprodan** [comment]
@dholbach this broke the tabs https://deploy-preview-1136--fluxcd.netlify.app/flux/installation/

**Comment by dholbach** [comment]
@kingdonb Pinging you as I'm not sure if it'll need changes to the `Dockerfile` - I personally don't use it for developing.

**Comment by stefanprodan** [comment]
Now I see lots of errors in the console around web fonts

**Comment by dholbach** [comment]
I let upstream know about the issue and updated Font-Awesome to what it needs to be (they need to update their respective `go.mod`).

**Comment by dholbach** [comment]
It works locally, but not on Netlify. I'll move this to draft mode for now.

**Comment by dholbach** [comment]
It's working now! :tada:

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @dholbach 🏅

**Pull request merged**
