### PR TITLE
Adding GitOps Days 2022 Videos

### PR DESCRIPTION
**Pull request by vanessaabankwah**
Signed-off-by: Vanessa Abankwah  <96237690+VanessaWeaveworksK8S@users.noreply.github.com>

### CODE REVIEW

**Review by scottrigby — CHANGES_REQUESTED** [review]
Found the issue: https://github.com/dcoapp/app/issues/151#issuecomment-1239481537

You can fix the existing PR with a local rebase and force push. The DCO bot details page has instructions how to do this:

> To add your Signed-off-by line to every commit in this branch:
>
> 1. Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
> 2. In your local branch, run: `git rebase HEAD~2 --signoff`
> 3. Force push your changes to overwrite the branch: `git push --force-with-lease origin patch-2`

Or you can fix your GitHub user display name (remove trailing space), close this PR and open a new one via the GitHub web UI.

**Review by scottrigby — APPROVED** [review]
Great job fixing! lgtm

**Review by scottrigby — DISMISSED** [review]
actually, broken links, don't merge yet 😅

**Review by vanessaabankwah — COMMENTED** [review]
@scottrigby please review

**Review by dholbach — APPROVED** [review]
Super, thank you very much!

**Pull request merged**
