### PR TITLE
Move Quivr to Flux2 adopters

### PR DESCRIPTION
**Pull request by Frederik-Baetens**
Signed-off-by: Frederik Baetens <baetens.fr@gmail.com>

If needed, i can convert the logo to png

### CODE REVIEW

**Review by hiddeco — COMMENTED** [review]
The `.svg` file indeed [does not seem to work](https://deploy-preview-293--fluxcd.netlify.app/adopters/).

Would accept a `.png` version, but a modification to the adopters logic so that it supports `.svg` files is also welcome :-)

**Comment by Frederik-Baetens** [comment]
I tacked on a fix for svgs not being properly sized. I think this issue is due to svgs not getting a proper size when embedded in a <p> element. This can also be fixed by setting a manual width in the svg, (such as width = 1000em), but this seemed more convenient for future contributors.

**Review by dholbach — APPROVED** [review]
Great work, you really went the extra mile!

**Comment by dholbach** [comment]
Apparently there's a small conflict in adopters/1-flux-v2.yaml now?

**Comment by Frederik-Baetens** [comment]
I've rebased to fix the merge conflict :)

**Comment by hiddeco** [comment]
Thank you @Frederik-Baetens :coffee:

**Pull request merged**
