### PR TITLE
Add MilliporeSigma to adopters

### PR DESCRIPTION
**Pull request by eravindar12**

### CODE REVIEW

**Comment by makkes** [comment]
Please follow all steps listed in https://fluxcd.io/contributing/flux-adopters/ to add your organization to the adopters page.

**Comment by eravindar12** [comment]
@makkes - Yes, I have followed all the instructions in the doc however still facing the same issue saying review is required and merging is blocked.
https://fluxcd.io/contributing/flux-adopters/

**Comment by makkes** [comment]
> @makkes - Yes, I have followed all the instructions in the doc however still facing the same issue saying review is required and merging is blocked.
> https://fluxcd.io/contributing/flux-adopters/

No you haven't. Merely adding your image is not enough.

**Comment by eravindar12** [comment]
Thanks @makkes - I got it there was some issue on my end the changes were not saved.
Now I've added the entry as per the doc instructions.

**Review by eravindar12 — COMMENTED** [review]
Updated and corrected the files

**Comment by eravindar12** [comment]
@makkes - Please review.

**Comment by kingdonb** [comment]
@eravindar12 There is a merge conflict in your branch, it looks like from here.

I will go ahead and push over it to resolve, so this can be merged 👍

**Comment by kingdonb** [comment]
Let's have a look at the deploy preview, and ...
Screenshot 2023-07-07 at 5 36 04 PM

Are you happy with the way this looks? What I mean basically, the card text is too wide for one line, but as an example in the neighboring card, we can add a hyphen so the line break goes between Millipore-Sigma
Screenshot 2023-07-07 at 5 36 40 PM

WDYT?

**Comment by eravindar12** [comment]
Hi @kingdonb - Yes, that would be great, and thanks!

**Comment by kingdonb** [comment]
I added a hyphen here in a34229ae

How does this look now:
Screenshot 2023-07-07 at 6 19 50 PM

Better dash or space? You'll have to let me know what makes sense for your branding.

I force pushed over your branch again in order to resolve the merge conflict, please check out my branch at a34229aeb677d176829a76a3f34f9651038bb46d if you have any changes and make them based on that fork. (I'm trying to keep the history linear, and avoid bringing the conflict back into the branch.)

Then once we've got all the changes in a reviewable + approved state, we should squash them so it's a single commit! OK? :)

**Comment by eravindar12** [comment]
@kingdonb - Actually, it's preferred to keep no spaces or dash instead keep the company name as MilliporeSigma because - "Merck acquired Sigma-Aldrich and merged it with Merck Millipore. In the United States and Canada, the life science business is known as MilliporeSigma(i.e., https://en.wikipedia.org/wiki/Merck_Millipore), and even the company logo - nowhere the name is separated.

` - name: MilliporeSigma
      url: https://www.sigmaaldrich.com/
      logo: logos/milliporesigma.png      `     
      
I made all the required changes in my previous commits so didn't think any changes were required on my end at the moment.
In case, if any changes require please let me know if not please approve and merge, thanks again!

**Comment by kingdonb** [comment]
OK, got it 👍 

I removed my commit and put back the un-conflicted branch with your changes only.

Screenshot 2023-07-07 at 7 11 57 PM

It comes out looking like this. If you confirm that looks OK, I think we'll squash and merge 👍

**Review by kingdonb — APPROVED** [review]

**Comment by eravindar12** [comment]
@kingdonb  - Yes, that LGTM 👍
                        Thanks!

**Pull request merged**
