### PR TITLE
Add OpsMx to adopters

### PR DESCRIPTION
**Pull request by rebalag**
Add OpsMx to adopters list

### CODE REVIEW

**Comment by stefanprodan** [comment]
Hey @rebalag I'm really confused, you stated on your website that OpsMx is [moving people off Flux](https://www.opsmx.com/news/opsmx-announces-new-enterprise-gitops-program-for-weaveworks-customers/) and here you are saying OpsMx has adopted Flux. The adopters page is for organisations who are using Flux in production, is OpsMx using Flux in this capacity?

**Comment by rebalag** [comment]
@stefanprodan We have Flux in production. OpsMx has OpenCD approach supporting enterprise customers with GitOps configurations, security and software delivery. We are also adding support to existing Flux deployments along with mix of other CD systems in enterprise. We will update the communication to reflect the change in support for and use of Flux project.

**Comment by stefanprodan** [comment]
What made you change your mind from moving people off Flux into supporting Flux?

**Comment by kingdonb** [comment]
I don't want to assume this is being submitted in bad faith, but

https://www.opsmx.com/blog/making-the-leap-transitioning-from-flux-to-argo-cd-for-gitops/
https://www.opsmx.com/news/opsmx-announces-new-enterprise-gitops-program-for-weaveworks-customers/
https://www.opsmx.com/blog/argo-cd-vs-flux-cd-best-tools-for-gitops/

https://www.google.com/search?q=site%3A+opsmx.com+flux

I don't find Flux on your website at all, except for these pages linked above, so it is hard to regard this as adoption in good faith, and not some type of marketing play that's plainly unrelated to Flux itself.

As far as I can tell, from reading the content on your website, your only publicized offering is designed to help migrate Flux users to ArgoCD... I'm not sure that's the kind of help we had in mind!

The information that compares Flux to Argo is also inaccurate (from the last link, which I have not reviewed in detail, but I found some substantial factual inaccuracies in it. Flux does not provide any sort of direct support jsonnet, for example.)

**Comment by rebalag** [comment]
To clarify, we have made a decision to support Flux and join the community that is different from past direction. Couple of articles point to our support for Flux. 
https://www.opsmx.com/blog/introducing-opsmx-support-for-flux-powering-seamless-gitops-workflows/
https://www.opsmx.com/blog/how-can-opsmx-assist-weaveworks-customers/
Will look into the comparison blog for accuracies and update

**Comment by kingdonb** [comment]
I apologize if I misinterpreted anything, it is OK if you change your stance 👍  glad that Open CD and OpsMX want to join us here

**Comment by kingdonb** [comment]
OK if I rebase this one on #1826 so that we don't get a conflict in the backport 👀

**Review by kingdonb — APPROVED** [review]
LGTM

**Comment by dommety** [comment]
@stefanprodan We are an Open CD company and our commitment to open source CD Platforms remains central to who we are.  After talking to several flux users and accessing our long term capabilities/constraints we  decided that  supporting Flux is the right direction in our journey. I shared  our intent and thinking  behind it in this blog https://www.opsmx.com/blog/announcing-opsmx-support-for-cncf-flux-an-important-step-for-open-cd/

Would love to hear your thoughts and happy to elaborate more.

**Pull request merged**
