### PR TITLE
add new resources from gitops one stop shop event

### PR DESCRIPTION
**Pull request by dholbach**
@staceypotter Is this all the ones you were expecting me to add?

### CODE REVIEW

**Comment by dholbach** [comment]
→ https://deploy-preview-643--fluxcd.netlify.app/resources/

**Comment by dholbach** [comment]
I added the missing video which @staceypotter noticed. Thanks for the feedback.

**Comment by staceypotter** [comment]
LGTM, thanks @dholbach!

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @dholbach and @staceypotter

**Pull request merged**
